"""Tech catalog (mirror of apworld/stellaris/data/tech_catalog.py).

This file is read by the runtime client (ap_bridge.py + slot_generator.py)
which lives in a separate distribution from the apworld. The two files MUST
stay byte-for-byte identical aside from this header — the offsets, item
IDs, and location IDs are derived from this data and a divergence between
client and apworld would silently corrupt seeds.

Sync command:
    cp apworld/stellaris/data/tech_catalog.py client/tech_catalog.py
"""

from typing import Dict, List, NamedTuple, Optional


class TechCatalogEntry(NamedTuple):
    key: str            # Stellaris tech key (e.g. "tech_synthetic_workers")
    display: str        # Human-readable name (e.g. "Synthetics")
    tier: int           # Stellaris tech tier (0-5)
    area: str           # "physics" | "society" | "engineering"
    prereqs: List[str]  # Vanilla tech prerequisites
    dlc: Optional[str]  # DLC short flag, or None for base game
    offset: int         # Stable ID offset — NEVER change after release
    category: str       # Stellaris tech category (e.g. "biology")
    is_rare: bool       # Whether the vanilla tech is rare
    is_dangerous: bool  # Whether researching it triggers a dangerous event


TECH_CATALOG: List[TechCatalogEntry] = [
    TechCatalogEntry('tech_adaptive_bureaucracy', 'Adaptive Bureaucracy', 1, 'society', ['tech_planetary_unification'], None, 0, 'statecraft', False, False),
    TechCatalogEntry('tech_adaptive_combat_algorithms', 'Adaptive Combat Algorithms', 2, 'society', [], None, 1, 'military_theory', False, False),
    TechCatalogEntry('tech_administrative_ai', 'Administrative AI', 1, 'physics', ['tech_basic_science_lab_1'], None, 2, 'computing', False, False),
    TechCatalogEntry('tech_advanced_industrial_storm_protection', 'Advanced Industrial Storm Protection', 2, 'engineering', ['tech_industrial_storm_protection'], None, 3, 'industry', False, False),
    TechCatalogEntry('tech_advanced_metallurgy_1', 'Advanced Metallurgy I', 2, 'engineering', ['tech_alloys_1', 'tech_ship_armor_2'], None, 4, 'materials', False, False),
    TechCatalogEntry('tech_advanced_metallurgy_2', 'Advanced Metallurgy II', 4, 'engineering', ['tech_advanced_metallurgy_1', 'tech_alloys_2', 'tech_ship_armor_4'], None, 5, 'materials', False, False),
    TechCatalogEntry('tech_advanced_storm_manipulation', 'Advanced Storm Manipulation', 3, 'physics', ['tech_storm_manipulation'], None, 6, 'field_manipulation', True, False),
    TechCatalogEntry('tech_afterburners_1', 'Afterburners I', 1, 'engineering', ['tech_thrusters_1'], None, 7, 'propulsion', False, False),
    TechCatalogEntry('tech_afterburners_2', 'Afterburners II', 3, 'engineering', ['tech_afterburners_1', 'tech_thrusters_3'], None, 8, 'propulsion', False, False),
    TechCatalogEntry('tech_akx_worm_1', 'Akx Worm I', 0, 'physics', [], None, 9, 'field_manipulation', True, False),
    TechCatalogEntry('tech_akx_worm_2', 'Akx Worm II', 0, 'society', [], None, 10, 'statecraft', True, False),
    TechCatalogEntry('tech_akx_worm_3', 'Akx Worm III', 0, 'physics', ['tech_akx_worm_1', 'tech_akx_worm_2'], None, 11, 'particles', True, True),
    TechCatalogEntry('tech_alien_cloning', 'Alien Cloning', 2, 'society', ['tech_gravity_wells'], None, 12, 'biology', False, False),
    TechCatalogEntry('tech_alien_life_studies', 'Alien Life Studies', 1, 'society', [], None, 13, 'biology', False, False),
    TechCatalogEntry('tech_alien_topography', 'Alien Topography', 2, 'society', [], 'first_contact', 14, 'new_worlds', False, False),
    TechCatalogEntry('tech_alloy_fossilization', 'Alloy Fossilization', 2, 'engineering', [], None, 15, 'materials', False, False),
    TechCatalogEntry('tech_alloys_1', 'Alloy Foundries', 1, 'engineering', ['tech_basic_industry'], None, 16, 'materials', False, False),
    TechCatalogEntry('tech_alloys_2', 'Advanced Alloys', 3, 'engineering', ['tech_alloys_1', 'tech_colonial_centralization'], None, 17, 'materials', False, False),
    TechCatalogEntry('tech_amoeba_strike_craft_1', 'Amoeba Strike Craft I', 2, 'society', [], None, 18, 'biology', False, False),
    TechCatalogEntry('tech_antimatter_power', 'Antimatter Power', 3, 'physics', ['tech_cold_fusion_power'], None, 19, 'particles', False, False),
    TechCatalogEntry('tech_arc_emitter_1', 'Arc Emitter I', 4, 'physics', ['tech_disruptors_3', 'tech_battleships', 'tech_stingers'], None, 20, 'particles', False, False),
    TechCatalogEntry('tech_arc_emitter_2', 'Arc Emitter II', 4, 'physics', ['tech_arc_emitter_1'], None, 21, 'particles', False, False),
    TechCatalogEntry('tech_arcane_deciphering', 'Arcane Deciphering', 2, 'society', [], 'ancient_relics', 22, 'archaeostudies', True, False),
    TechCatalogEntry('tech_archaeo_detection_scrambler', 'Archaeo Detection Scrambler', 4, 'society', ['tech_archaeostudies'], 'ancient_relics', 23, 'archaeostudies', True, False),
    TechCatalogEntry('tech_archaeo_lasers', 'Archaeo Lasers', 3, 'society', ['tech_archaeostudies'], 'ancient_relics', 24, 'archaeostudies', True, False),
    TechCatalogEntry('tech_archaeo_mass_accelerator', 'Archaeo Mass Accelerator', 3, 'society', ['tech_archaeostudies'], 'ancient_relics', 25, 'archaeostudies', True, False),
    TechCatalogEntry('tech_archaeo_mass_drivers', 'Archaeo Mass Drivers', 3, 'society', ['tech_archaeostudies'], 'ancient_relics', 26, 'archaeostudies', True, False),
    TechCatalogEntry('tech_archaeo_missiles', 'Archaeo Missiles', 3, 'society', ['tech_archaeostudies'], 'ancient_relics', 27, 'archaeostudies', True, False),
    TechCatalogEntry('tech_archaeo_overcharger', 'Archaeo Overcharger', 3, 'society', ['tech_archaeostudies'], 'ancient_relics', 28, 'archaeostudies', True, False),
    TechCatalogEntry('tech_archaeo_pk_devolving_beam', 'Archaeo Pk Devolving Beam', 5, 'society', [], 'ancient_relics', 29, 'archaeostudies', True, False),
    TechCatalogEntry('tech_archaeo_point_defence', 'Archaeo Point Defence', 3, 'society', ['tech_archaeostudies'], 'ancient_relics', 30, 'archaeostudies', True, False),
    TechCatalogEntry('tech_archaeo_rampart', 'Archaeo Rampart', 3, 'society', ['tech_archaeostudies'], 'ancient_relics', 31, 'archaeostudies', True, False),
    TechCatalogEntry('tech_archaeo_refinery', 'Archaeo Refinery', 3, 'society', ['tech_archaeostudies'], 'ancient_relics', 32, 'archaeostudies', True, False),
    TechCatalogEntry('tech_archaeo_strike_crafts', 'Archaeo Strike Crafts', 3, 'society', ['tech_archaeostudies'], 'ancient_relics', 33, 'archaeostudies', True, False),
    TechCatalogEntry('tech_archaeo_titan_beam', 'Archaeo Titan Beam', 4, 'society', ['tech_archaeostudies'], 'ancient_relics', 34, 'archaeostudies', True, False),
    TechCatalogEntry('tech_archaeoarmor', 'Archaeoarmor', 3, 'society', ['tech_archaeostudies'], 'ancient_relics', 35, 'archaeostudies', True, False),
    TechCatalogEntry('tech_archaeoshield', 'Archaeoshield', 3, 'society', ['tech_archaeostudies'], 'ancient_relics', 36, 'archaeostudies', True, False),
    TechCatalogEntry('tech_archaeostudies', 'Archaeostudies', 2, 'society', [], 'ancient_relics', 37, 'archaeostudies', True, False),
    TechCatalogEntry('tech_archeology_lab', 'Archeology Lab', 2, 'physics', [], None, 38, 'computing', True, False),
    TechCatalogEntry('tech_archeology_lab_ancrel', 'Archeology Lab Ancrel', 2, 'society', [], 'ancient_relics', 39, 'archaeostudies', True, False),
    TechCatalogEntry('tech_armor_hardeners_1', 'Armor Hardeners I', 2, 'engineering', ['tech_advanced_metallurgy_1', 'tech_rare_crystals'], None, 40, 'materials', False, False),
    TechCatalogEntry('tech_armor_hardeners_2', 'Armor Hardeners II', 5, 'engineering', ['tech_armor_hardeners_1', 'tech_mine_living_metal'], None, 41, 'materials', False, False),
    TechCatalogEntry('tech_artificial_moral_codes', 'Artificial Moral Codes', 2, 'society', [], None, 42, 'statecraft', False, False),
    TechCatalogEntry('tech_ascension_theory', 'Ascension Theory', 4, 'society', [], None, 43, 'statecraft', True, False),
    TechCatalogEntry('tech_assembly_pattern', 'Assembly Pattern', 2, 'engineering', [], None, 44, 'industry', False, False),
    TechCatalogEntry('tech_assisted_detection', 'Assisted Detection', 2, 'physics', ['tech_detection_array'], 'first_contact', 45, 'computing', True, False),
    TechCatalogEntry('tech_asteroidal_carapace', 'Asteroidal Carapace', 3, 'engineering', [], None, 46, 'materials', False, False),
    TechCatalogEntry('tech_astral_harvesting', 'Astral Harvesting', 2, 'physics', [], 'astral_planes', 47, 'particles', False, False),
    TechCatalogEntry('tech_atmospheric_orbital_mechanics', 'Atmospheric Orbital Mechanics', 2, 'physics', [], 'first_contact', 48, 'computing', False, False),
    TechCatalogEntry('tech_aura_intensification', 'Aura Intensification', 4, 'society', ['tech_psionic_aura'], None, 49, 'psionics', True, False),
    TechCatalogEntry('tech_aura_resonation', 'Aura Resonation', 3, 'society', ['tech_psionic_aura'], None, 50, 'psionics', True, False),
    TechCatalogEntry('tech_autocannons_1', 'Autocannons I', 2, 'engineering', ['tech_mass_drivers_2'], None, 51, 'propulsion', False, False),
    TechCatalogEntry('tech_autocannons_2', 'Autocannons II', 3, 'engineering', ['tech_autocannons_1'], None, 52, 'propulsion', False, False),
    TechCatalogEntry('tech_autocannons_3', 'Autocannons III', 4, 'engineering', ['tech_autocannons_2'], None, 53, 'propulsion', False, False),
    TechCatalogEntry('tech_autocurating_vault', 'Autocurating Vault', 3, 'society', ['tech_administrative_ai', 'tech_colonial_centralization'], None, 54, 'statecraft', False, False),
    TechCatalogEntry('tech_automated_exploration', 'Automated Exploration', 1, 'physics', [], None, 55, 'computing', False, False),
    TechCatalogEntry('tech_autonomous_agents', 'Autonomous Agents', 2, 'society', ['tech_colonial_centralization'], None, 56, 'statecraft', False, False),
    TechCatalogEntry('tech_auxiliary_fire_control', 'Auxiliary Fire Control', 1, 'physics', ['tech_combat_computers_1'], None, 57, 'computing', False, False),
    TechCatalogEntry('tech_basic_science_lab_2', 'Basic Science Lab II', 1, 'physics', ['tech_basic_science_lab_1'], None, 58, 'computing', False, False),
    TechCatalogEntry('tech_basic_science_lab_3', 'Basic Science Lab III', 3, 'physics', ['tech_basic_science_lab_2', 'tech_colonial_centralization'], None, 59, 'computing', False, False),
    TechCatalogEntry('tech_battleship_build_speed', 'Battleship Build Speed', 4, 'engineering', ['tech_battleships'], None, 60, 'voidcraft', False, False),
    TechCatalogEntry('tech_battleship_hull_1', 'Battleship Hull I', 4, 'engineering', ['tech_battleships'], None, 61, 'voidcraft', False, False),
    TechCatalogEntry('tech_battleship_hull_2', 'Battleship Hull II', 5, 'engineering', ['tech_battleship_hull_1'], None, 62, 'voidcraft', True, False),
    TechCatalogEntry('tech_battleships', 'Battleships', 4, 'engineering', ['tech_cruisers'], None, 63, 'voidcraft', False, False),
    TechCatalogEntry('tech_binary_motivators', 'Binary Motivators', 3, 'engineering', ['tech_colonial_centralization', 'tech_robomodding_m'], None, 64, 'industry', False, False),
    TechCatalogEntry('tech_bio_reactor', 'Bio Reactor', 1, 'society', ['tech_industrial_farming'], None, 65, 'biology', True, False),
    TechCatalogEntry('tech_bio_reactor_2', 'Bio Reactor II', 2, 'society', ['tech_bio_reactor'], None, 66, 'biology', True, False),
    TechCatalogEntry('tech_biomechanics', 'Biomechanics', 4, 'society', ['tech_adaptive_combat_algorithms'], None, 67, 'biology', True, False),
    TechCatalogEntry('tech_boarding_cables', 'Boarding Cables', 1, 'engineering', [], None, 68, 'propulsion', False, False),
    TechCatalogEntry('tech_btc_1', 'Btc I', 5, 'engineering', [], 'apocalypse', 69, 'voidcraft', True, False),
    TechCatalogEntry('tech_capacity_boosters', 'Capacity Boosters', 4, 'society', ['tech_selected_lineages'], None, 70, 'biology', True, False),
    TechCatalogEntry('tech_capital_productivity_1', 'Capital Productivity I', 2, 'society', ['tech_planetary_unification'], None, 71, 'statecraft', False, False),
    TechCatalogEntry('tech_capital_productivity_2', 'Capital Productivity II', 3, 'society', ['tech_colonial_centralization', 'tech_capital_productivity_1'], None, 72, 'statecraft', False, False),
    TechCatalogEntry('tech_capital_productivity_3', 'Capital Productivity III', 4, 'society', ['tech_galactic_administration', 'tech_capital_productivity_2'], None, 73, 'statecraft', False, False),
    TechCatalogEntry('tech_centralized_command', 'Centralized Command', 3, 'society', [], None, 74, 'military_theory', False, False),
    TechCatalogEntry('tech_climate_restoration', 'Climate Restoration', 4, 'society', ['tech_terrestrial_sculpting'], None, 75, 'new_worlds', False, False),
    TechCatalogEntry('tech_cloaking_1', 'Cloaking I', 2, 'physics', ['tech_shields_2'], 'first_contact', 76, 'field_manipulation', True, False),
    TechCatalogEntry('tech_cloaking_2', 'Cloaking II', 3, 'physics', ['tech_cloaking_1', 'tech_shields_3'], 'first_contact', 77, 'field_manipulation', True, False),
    TechCatalogEntry('tech_cloaking_3', 'Cloaking III', 4, 'physics', ['tech_cloaking_2', 'tech_shields_4'], 'first_contact', 78, 'field_manipulation', True, False),
    TechCatalogEntry('tech_cloaking_dark_matter', 'Cloaking Dark Matter', 0, 'physics', ['tech_dark_matter_deflector', 'tech_cloaking_3'], 'first_contact', 79, 'field_manipulation', True, True),
    TechCatalogEntry('tech_cloaking_psi', 'Cloaking Psi', 5, 'society', ['tech_psi_jump_drive_1'], 'first_contact', 80, 'psionics', True, False),
    TechCatalogEntry('tech_cloning', 'Cloning', 2, 'society', ['tech_genome_mapping'], None, 81, 'biology', False, False),
    TechCatalogEntry('tech_cold_fusion_power', 'Cold Fusion Power', 2, 'physics', ['tech_fusion_power'], None, 82, 'particles', False, False),
    TechCatalogEntry('tech_collective_production_methods', 'Collective Production Methods', 3, 'society', ['tech_unity_of_purpose'], None, 83, 'statecraft', False, False),
    TechCatalogEntry('tech_collective_self', 'Collective Self', 3, 'society', ['tech_colonial_centralization'], None, 84, 'statecraft', False, False),
    TechCatalogEntry('tech_colonial_bureaucracy', 'Colonial Bureaucracy', 2, 'society', ['tech_adaptive_bureaucracy'], None, 85, 'statecraft', False, False),
    TechCatalogEntry('tech_colonial_centralization', 'Colonial Centralization', 2, 'society', ['tech_planetary_unification'], None, 86, 'new_worlds', False, False),
    TechCatalogEntry('tech_colonization_2', 'Colonization II', 2, 'society', ['tech_colonization_1'], None, 87, 'new_worlds', False, False),
    TechCatalogEntry('tech_colonization_3', 'Colonization III', 2, 'society', ['tech_colonization_2'], None, 88, 'new_worlds', False, False),
    TechCatalogEntry('tech_colonization_4', 'Colonization IV', 3, 'society', ['tech_colonization_3'], None, 89, 'new_worlds', False, False),
    TechCatalogEntry('tech_colonization_5', 'Colonization V', 4, 'society', ['tech_colonization_4'], None, 90, 'new_worlds', False, False),
    TechCatalogEntry('tech_colossus', 'Colossus', 5, 'engineering', ['tech_titans'], 'apocalypse', 91, 'voidcraft', True, False),
    TechCatalogEntry('tech_combat_computers_1', 'Combat Computers I', 1, 'physics', ['tech_administrative_ai'], None, 92, 'computing', False, False),
    TechCatalogEntry('tech_combat_computers_2', 'Combat Computers II', 3, 'physics', ['tech_combat_computers_1', 'tech_self_aware_logic'], None, 93, 'computing', False, False),
    TechCatalogEntry('tech_combat_computers_3', 'Combat Computers III', 4, 'physics', ['tech_combat_computers_2', 'tech_sapient_ai'], None, 94, 'computing', True, True),
    TechCatalogEntry('tech_combat_computers_autonomous', 'Combat Computers Autonomous', 4, 'physics', ['tech_combat_computers_2'], None, 95, 'computing', True, False),
    TechCatalogEntry('tech_combat_computers_bio_integration', 'Combat Computers Bio Integration', 2, 'physics', ['tech_controlled_mutations'], None, 96, 'computing', False, False),
    TechCatalogEntry('tech_combat_training', 'Combat Training', 3, 'society', ['tech_centralized_command'], None, 97, 'military_theory', False, False),
    TechCatalogEntry('tech_command_matrix', 'Command Matrix', 3, 'society', ['tech_refit_standards'], None, 98, 'military_theory', False, False),
    TechCatalogEntry('tech_compact_living', 'Compact Living', 2, 'society', [], 'first_contact', 99, 'statecraft', False, False),
    TechCatalogEntry('tech_consecration_fields', 'Consecration Fields', 3, 'society', ['tech_holographic_rituals', 'tech_colonial_centralization'], None, 100, 'statecraft', False, False),
    TechCatalogEntry('tech_construction_templates', 'Construction Templates', 4, 'engineering', ['tech_assembly_pattern'], None, 101, 'industry', True, False),
    TechCatalogEntry('tech_consumer_good_refinement_1', 'Consumer Good Refinement I', 2, 'physics', ['tech_luxuries_1', 'tech_administrative_ai'], None, 102, 'computing', False, False),
    TechCatalogEntry('tech_consumer_good_refinement_2', 'Consumer Good Refinement II', 4, 'physics', ['tech_luxuries_2', 'tech_consumer_good_refinement_1', 'tech_self_aware_logic'], None, 103, 'computing', False, False),
    TechCatalogEntry('tech_containment_vessel', 'Containment Vessel', 3, 'physics', ['tech_gravity_wells'], None, 104, 'field_manipulation', True, False),
    TechCatalogEntry('tech_controlled_mutations', 'Controlled Mutations', 2, 'society', ['tech_alien_cloning'], None, 105, 'biology', False, False),
    TechCatalogEntry('tech_controlled_mutations_2', 'Controlled Mutations II', 4, 'society', ['tech_controlled_mutations'], None, 106, 'biology', False, False),
    TechCatalogEntry('tech_corvette_build_speed', 'Corvette Build Speed', 1, 'engineering', ['tech_corvettes'], None, 107, 'voidcraft', False, False),
    TechCatalogEntry('tech_corvette_hull_1', 'Corvette Hull I', 1, 'engineering', ['tech_corvettes'], None, 108, 'voidcraft', False, False),
    TechCatalogEntry('tech_corvette_hull_2', 'Corvette Hull II', 2, 'engineering', ['tech_corvette_hull_1'], None, 109, 'voidcraft', True, False),
    TechCatalogEntry('tech_cosmogenesis_FE_titan', 'Cosmogenesis Fe Titan', 5, 'engineering', [], 'machine_age', 110, 'voidcraft', True, True),
    TechCatalogEntry('tech_cosmogenesis_battlecruiser', 'Cosmogenesis Battlecruiser', 5, 'engineering', [], 'machine_age', 111, 'voidcraft', True, True),
    TechCatalogEntry('tech_cosmogenesis_crisis_1', 'Cosmogenesis Crisis I', 5, 'physics', [], 'machine_age', 112, 'computing', True, False),
    TechCatalogEntry('tech_cosmogenesis_crisis_2', 'Cosmogenesis Crisis II', 5, 'physics', [], 'machine_age', 113, 'computing', True, False),
    TechCatalogEntry('tech_cosmogenesis_crisis_3', 'Cosmogenesis Crisis III', 5, 'physics', [], 'machine_age', 114, 'computing', True, False),
    TechCatalogEntry('tech_cosmogenesis_crisis_4', 'Cosmogenesis Crisis IV', 5, 'physics', [], 'machine_age', 115, 'computing', True, False),
    TechCatalogEntry('tech_cosmogenesis_crisis_5', 'Cosmogenesis Crisis V', 5, 'physics', [], 'machine_age', 116, 'computing', True, False),
    TechCatalogEntry('tech_cosmogenesis_escort', 'Cosmogenesis Escort', 5, 'engineering', [], 'machine_age', 117, 'voidcraft', True, True),
    TechCatalogEntry('tech_cosmogenesis_harbinger', 'Cosmogenesis Harbinger', 5, 'society', [], 'machine_age', 118, 'biology', True, True),
    TechCatalogEntry('tech_cosmogenesis_mauler', 'Cosmogenesis Mauler', 5, 'society', [], 'machine_age', 119, 'biology', True, True),
    TechCatalogEntry('tech_cosmogenesis_stinger', 'Cosmogenesis Stinger', 5, 'society', [], 'machine_age', 120, 'biology', True, True),
    TechCatalogEntry('tech_cosmogenesis_thesis', 'Cosmogenesis Thesis', 4, 'physics', [], 'machine_age', 121, 'computing', False, True),
    TechCatalogEntry('tech_cosmogenesis_weaver', 'Cosmogenesis Weaver', 5, 'society', [], 'machine_age', 122, 'biology', True, True),
    TechCatalogEntry('tech_cosmogenesis_world', 'Cosmogenesis World', 5, 'engineering', [], 'machine_age', 123, 'materials', True, False),
    TechCatalogEntry('tech_covenant_composer', 'Covenant Composer', 0, 'society', ['tech_psionic_theory'], None, 124, 'psionics', True, False),
    TechCatalogEntry('tech_covenant_cradle', 'Covenant Cradle', 0, 'society', ['tech_psionic_theory'], None, 125, 'psionics', True, False),
    TechCatalogEntry('tech_covenant_eater', 'Covenant Eater', 0, 'society', ['tech_psionic_theory'], None, 126, 'psionics', True, False),
    TechCatalogEntry('tech_covenant_instrument', 'Covenant Instrument', 0, 'society', ['tech_psionic_theory'], None, 127, 'psionics', True, False),
    TechCatalogEntry('tech_covenant_whisperers', 'Covenant Whisperers', 0, 'society', ['tech_psionic_theory'], None, 128, 'psionics', True, False),
    TechCatalogEntry('tech_cruiser_build_speed', 'Cruiser Build Speed', 3, 'engineering', ['tech_cruisers'], None, 129, 'voidcraft', False, False),
    TechCatalogEntry('tech_cruiser_hull_1', 'Cruiser Hull I', 3, 'engineering', ['tech_cruisers'], None, 130, 'voidcraft', False, False),
    TechCatalogEntry('tech_cruiser_hull_2', 'Cruiser Hull II', 4, 'engineering', ['tech_cruiser_hull_1'], None, 131, 'voidcraft', True, False),
    TechCatalogEntry('tech_cruisers', 'Cruisers', 3, 'engineering', ['tech_destroyers'], None, 132, 'voidcraft', False, False),
    TechCatalogEntry('tech_cryostasis_1', 'Cryostasis I', 1, 'physics', ['tech_administrative_ai', 'tech_colonization_1'], None, 133, 'computing', False, False),
    TechCatalogEntry('tech_cryostasis_2', 'Cryostasis II', 3, 'physics', ['tech_self_aware_logic', 'tech_cryostasis_1'], None, 134, 'computing', False, False),
    TechCatalogEntry('tech_cryovault', 'Cryovault', 2, 'society', [], None, 135, 'new_worlds', False, False),
    TechCatalogEntry('tech_crystal_armor_1', 'Crystal Armor I', 2, 'engineering', [], None, 136, 'materials', False, False),
    TechCatalogEntry('tech_crystal_armor_2', 'Crystal Armor II', 4, 'engineering', [], None, 137, 'materials', True, False),
    TechCatalogEntry('tech_cultural_heritage', 'Cultural Heritage', 1, 'society', ['tech_planetary_unification'], None, 138, 'statecraft', False, False),
    TechCatalogEntry('tech_curator_lab', 'Curator Lab', 2, 'physics', [], None, 139, 'computing', True, False),
    TechCatalogEntry('tech_dangerous_wildlife', 'Dangerous Wildlife', 2, 'society', ['tech_colonization_1'], None, 140, 'new_worlds', False, False),
    TechCatalogEntry('tech_dark_matter_deflector', 'Dark Matter Deflector', 0, 'physics', ['tech_shields_5'], None, 141, 'field_manipulation', True, True),
    TechCatalogEntry('tech_dark_matter_detection', 'Dark Matter Detection', 5, 'physics', ['tech_detection_array', 'tech_mine_dark_matter'], 'first_contact', 142, 'particles', True, False),
    TechCatalogEntry('tech_dark_matter_power_core', 'Dark Matter Power Core', 0, 'physics', ['tech_zero_point_power'], None, 143, 'particles', True, True),
    TechCatalogEntry('tech_dark_matter_propulsion', 'Dark Matter Propulsion', 0, 'engineering', ['tech_thrusters_4'], None, 144, 'propulsion', True, True),
    TechCatalogEntry('tech_decryption_1', 'Decryption I', 1, 'physics', ['tech_colonial_bureaucracy'], None, 145, 'computing', False, False),
    TechCatalogEntry('tech_decryption_2', 'Decryption II', 2, 'physics', ['tech_decryption_1'], None, 146, 'computing', False, False),
    TechCatalogEntry('tech_decryption_3', 'Decryption III', 4, 'physics', ['tech_decryption_2'], None, 147, 'computing', False, False),
    TechCatalogEntry('tech_deep_sinkhole', 'Deep Sinkhole', 1, 'society', ['tech_colonization_1'], None, 148, 'new_worlds', False, False),
    TechCatalogEntry('tech_deep_space_citadel', 'Deep Space Citadel', 3, 'society', ['tech_starbase_3'], None, 149, 'military_theory', True, False),
    TechCatalogEntry('tech_defense_platform_hull_1', 'Defense Platform Hull I', 2, 'engineering', ['tech_starbase_3'], None, 150, 'voidcraft', True, False),
    TechCatalogEntry('tech_dense_jungle', 'Dense Jungle', 1, 'society', ['tech_colonization_1'], None, 151, 'new_worlds', False, False),
    TechCatalogEntry('tech_destroyer_build_speed', 'Destroyer Build Speed', 2, 'engineering', ['tech_destroyers'], None, 152, 'voidcraft', False, False),
    TechCatalogEntry('tech_destroyer_hull_1', 'Destroyer Hull I', 2, 'engineering', ['tech_destroyers'], None, 153, 'voidcraft', False, False),
    TechCatalogEntry('tech_destroyer_hull_2', 'Destroyer Hull II', 3, 'engineering', ['tech_destroyer_hull_1'], None, 154, 'voidcraft', True, False),
    TechCatalogEntry('tech_destroyers', 'Destroyers', 2, 'engineering', ['tech_corvettes'], None, 155, 'voidcraft', False, False),
    TechCatalogEntry('tech_detection_array', 'Detection Array', 2, 'physics', ['tech_sensors_2'], 'first_contact', 156, 'computing', True, False),
    TechCatalogEntry('tech_disruptors_1', 'Disruptors I', 2, 'physics', ['tech_lasers_2'], None, 157, 'particles', False, False),
    TechCatalogEntry('tech_disruptors_2', 'Disruptors II', 3, 'physics', ['tech_disruptors_1'], None, 158, 'particles', False, False),
    TechCatalogEntry('tech_disruptors_3', 'Disruptors III', 4, 'physics', ['tech_disruptors_2'], None, 159, 'particles', False, False),
    TechCatalogEntry('tech_doctrine_fleet_size_1', 'Fleet Size I', 1, 'society', [], None, 160, 'military_theory', False, False),
    TechCatalogEntry('tech_doctrine_fleet_size_2', 'Fleet Size II', 2, 'society', ['tech_doctrine_fleet_size_1'], None, 161, 'military_theory', False, False),
    TechCatalogEntry('tech_doctrine_fleet_size_3', 'Fleet Size III', 3, 'society', ['tech_doctrine_fleet_size_2'], None, 162, 'military_theory', False, False),
    TechCatalogEntry('tech_doctrine_fleet_size_4', 'Fleet Size IV', 4, 'society', ['tech_doctrine_fleet_size_3'], None, 163, 'military_theory', False, False),
    TechCatalogEntry('tech_doctrine_fleet_size_5', 'Fleet Size V', 5, 'society', ['tech_doctrine_fleet_size_4'], None, 164, 'military_theory', False, False),
    TechCatalogEntry('tech_doctrine_navy_size_1', 'Navy Size I', 1, 'society', [], None, 165, 'military_theory', False, False),
    TechCatalogEntry('tech_doctrine_navy_size_2', 'Navy Size II', 2, 'society', ['tech_doctrine_navy_size_1'], None, 166, 'military_theory', False, False),
    TechCatalogEntry('tech_doctrine_navy_size_3', 'Navy Size III', 3, 'society', ['tech_doctrine_navy_size_2'], None, 167, 'military_theory', False, False),
    TechCatalogEntry('tech_doctrine_navy_size_4', 'Navy Size IV', 4, 'society', ['tech_doctrine_navy_size_3'], None, 168, 'military_theory', False, False),
    TechCatalogEntry('tech_dragon_armor', 'Dragon Armor', 0, 'engineering', [], None, 169, 'materials', True, False),
    TechCatalogEntry('tech_droid_workers', 'Droids', 2, 'engineering', ['tech_robotic_workers', 'tech_colonial_centralization'], None, 170, 'industry', False, False),
    TechCatalogEntry('tech_dyson_sphere', 'Dyson Sphere', 5, 'physics', ['tech_mega_engineering'], None, 171, 'field_manipulation', True, False),
    TechCatalogEntry('tech_dyson_swarm', 'Dyson Swarm', 2, 'physics', [], 'machine_age', 172, 'computing', True, False),
    TechCatalogEntry('tech_eco_simulation', 'Eco Simulation', 1, 'society', ['tech_industrial_farming'], None, 173, 'biology', False, False),
    TechCatalogEntry('tech_ecological_adaptation', 'Ecological Adaptation', 3, 'society', ['tech_terrestrial_sculpting'], None, 174, 'new_worlds', False, False),
    TechCatalogEntry('tech_effective_bureaucracy', 'Effective Bureaucracy', 2, 'society', ['tech_adaptive_bureaucracy'], None, 175, 'statecraft', False, False),
    TechCatalogEntry('tech_embodied_dynamism', 'Embodied Dynamism', 3, 'society', ['tech_autonomous_agents'], None, 176, 'statecraft', False, False),
    TechCatalogEntry('tech_encryption_1', 'Encryption I', 1, 'physics', ['tech_colonial_bureaucracy'], None, 177, 'computing', False, False),
    TechCatalogEntry('tech_encryption_2', 'Encryption II', 2, 'physics', ['tech_encryption_1'], None, 178, 'computing', False, False),
    TechCatalogEntry('tech_encryption_3', 'Encryption III', 4, 'physics', ['tech_encryption_2'], None, 179, 'computing', False, False),
    TechCatalogEntry('tech_energy_lance_1', 'Energy Lance I', 4, 'physics', ['tech_lasers_4', 'tech_battleships', 'tech_stingers'], None, 180, 'particles', False, False),
    TechCatalogEntry('tech_energy_lance_2', 'Energy Lance II', 4, 'physics', ['tech_lasers_5', 'tech_energy_lance_1'], None, 181, 'particles', False, False),
    TechCatalogEntry('tech_energy_torpedoes_1', 'Energy Torpedoes I', 3, 'physics', ['tech_lasers_4', 'tech_torpedoes_1', 'tech_harbingers'], None, 182, 'particles', False, False),
    TechCatalogEntry('tech_energy_torpedoes_2', 'Energy Torpedoes II', 4, 'physics', ['tech_energy_torpedoes_1'], None, 183, 'particles', False, False),
    TechCatalogEntry('tech_engineering_1', 'Engineering I', 1, 'engineering', ['tech_basic_science_lab_1'], None, 184, 'materials', False, False),
    TechCatalogEntry('tech_engineering_2', 'Engineering II', 2, 'engineering', ['tech_engineering_1'], None, 185, 'materials', False, False),
    TechCatalogEntry('tech_engineering_3', 'Engineering III', 3, 'engineering', ['tech_engineering_2'], None, 186, 'materials', False, False),
    TechCatalogEntry('tech_enhanced_cryosleep_sedatives', 'Enhanced Cryosleep Sedatives', 2, 'society', [], None, 187, 'biology', False, False),
    TechCatalogEntry('tech_enigmatic_decoder', 'Enigmatic Decoder', 0, 'physics', [], None, 188, 'computing', True, False),
    TechCatalogEntry('tech_enigmatic_encoder', 'Enigmatic Encoder', 0, 'physics', [], None, 189, 'computing', True, False),
    TechCatalogEntry('tech_epigenetic_triggers', 'Epigenetic Triggers', 2, 'society', ['tech_genome_mapping'], None, 190, 'biology', False, False),
    TechCatalogEntry('tech_executive_retreat', 'Executive Retreat', 3, 'society', [], 'megacorp', 191, 'statecraft', False, False),
    TechCatalogEntry('tech_existential_campaigns', 'Existential Campaigns', 5, 'society', ['tech_galactic_campaigns'], None, 192, 'military_theory', True, True),
    TechCatalogEntry('tech_exotic_gases', 'Exotic Gases', 2, 'engineering', ['tech_basic_industry'], None, 193, 'materials', False, False),
    TechCatalogEntry('tech_experimental_subspace_navigation', 'Experimental Subspace Navigation', 2, 'physics', ['tech_sensors_2'], 'distant_stars', 194, 'field_manipulation', True, False),
    TechCatalogEntry('tech_extradimensional_weapon_1', 'Extradimensional Weapon I', 5, 'physics', [], None, 195, 'particles', True, False),
    TechCatalogEntry('tech_fe_administration_1', 'Fe Administration I', 0, 'society', [], None, 196, 'statecraft', True, True),
    TechCatalogEntry('tech_fe_administration_2', 'Fe Administration II', 0, 'society', ['tech_fe_administration_1'], None, 197, 'statecraft', True, True),
    TechCatalogEntry('tech_fe_affluence_1', 'Fe Affluence I', 0, 'engineering', [], None, 198, 'industry', True, True),
    TechCatalogEntry('tech_fe_affluence_2', 'Fe Affluence II', 0, 'engineering', ['tech_fe_affluence_1'], None, 199, 'industry', True, True),
    TechCatalogEntry('tech_fe_assembly_1', 'Fe Assembly I', 0, 'engineering', ['tech_robomodding', 'tech_robomodding_m'], None, 200, 'industry', True, True),
    TechCatalogEntry('tech_fe_assembly_2', 'Fe Assembly II', 0, 'engineering', ['tech_fe_assembly_1'], None, 201, 'industry', True, True),
    TechCatalogEntry('tech_fe_clinic_1', 'Fe Clinic I', 0, 'society', [], None, 202, 'biology', True, True),
    TechCatalogEntry('tech_fe_clinic_2', 'Fe Clinic II', 0, 'society', ['tech_fe_clinic_1'], None, 203, 'biology', True, True),
    TechCatalogEntry('tech_fe_dome_1', 'Fe Dome I', 0, 'society', [], None, 204, 'statecraft', True, True),
    TechCatalogEntry('tech_fe_dome_2', 'Fe Dome II', 0, 'society', ['tech_fe_dome_1'], None, 205, 'statecraft', True, True),
    TechCatalogEntry('tech_fe_entertainment_1', 'Fe Entertainment I', 0, 'society', [], None, 206, 'statecraft', True, True),
    TechCatalogEntry('tech_fe_entertainment_2', 'Fe Entertainment II', 0, 'society', ['tech_fe_entertainment_1'], None, 207, 'statecraft', True, True),
    TechCatalogEntry('tech_fe_fabricator_1', 'Fe Fabricator I', 0, 'engineering', [], None, 208, 'materials', True, True),
    TechCatalogEntry('tech_fe_fabricator_2', 'Fe Fabricator II', 0, 'engineering', ['tech_fe_fabricator_1'], None, 209, 'materials', True, True),
    TechCatalogEntry('tech_fe_forge_1', 'Fe Forge I', 0, 'engineering', [], None, 210, 'industry', True, True),
    TechCatalogEntry('tech_fe_forge_2', 'Fe Forge II', 0, 'engineering', ['tech_fe_forge_1'], None, 211, 'industry', True, True),
    TechCatalogEntry('tech_fe_fortress_1', 'Fe Fortress I', 0, 'society', [], None, 212, 'military_theory', True, True),
    TechCatalogEntry('tech_fe_fortress_2', 'Fe Fortress II', 0, 'society', ['tech_fe_fortress_1'], None, 213, 'military_theory', True, True),
    TechCatalogEntry('tech_fe_lab_1', 'Fe Lab I', 0, 'physics', [], None, 214, 'computing', True, True),
    TechCatalogEntry('tech_fe_lab_2', 'Fe Lab II', 0, 'physics', ['tech_fe_lab_1'], None, 215, 'computing', True, True),
    TechCatalogEntry('tech_fe_market_1', 'Fe Market I', 0, 'society', [], None, 216, 'statecraft', True, True),
    TechCatalogEntry('tech_fe_market_2', 'Fe Market II', 0, 'society', ['tech_fe_market_1'], None, 217, 'statecraft', True, True),
    TechCatalogEntry('tech_fe_mine_1', 'Fe Mine I', 0, 'engineering', [], None, 218, 'materials', True, True),
    TechCatalogEntry('tech_fe_mine_2', 'Fe Mine II', 0, 'engineering', ['tech_fe_mine_1'], None, 219, 'materials', True, True),
    TechCatalogEntry('tech_fe_nourishment_1', 'Fe Nourishment I', 0, 'society', [], None, 220, 'biology', True, True),
    TechCatalogEntry('tech_fe_nourishment_2', 'Fe Nourishment II', 0, 'society', ['tech_fe_nourishment_1'], None, 221, 'biology', True, True),
    TechCatalogEntry('tech_fe_security_1', 'Fe Security I', 0, 'society', [], None, 222, 'statecraft', True, True),
    TechCatalogEntry('tech_fe_security_2', 'Fe Security II', 0, 'society', ['tech_fe_security_1'], None, 223, 'statecraft', True, True),
    TechCatalogEntry('tech_fe_silo_1', 'Fe Silo I', 0, 'physics', [], None, 224, 'field_manipulation', True, True),
    TechCatalogEntry('tech_fe_silo_2', 'Fe Silo II', 0, 'physics', ['tech_fe_silo_1'], None, 225, 'field_manipulation', True, True),
    TechCatalogEntry('tech_fe_singularity_1', 'Fe Singularity I', 0, 'physics', [], None, 226, 'particles', True, True),
    TechCatalogEntry('tech_fe_singularity_2', 'Fe Singularity II', 0, 'physics', ['tech_fe_singularity_1'], None, 227, 'particles', True, True),
    TechCatalogEntry('tech_federation_code', 'Federation Code', 1, 'society', ['tech_colonial_centralization'], None, 228, 'statecraft', False, False),
    TechCatalogEntry('tech_flak_batteries_2', 'Flak Batteries II', 3, 'engineering', ['tech_flak_batteries_1'], None, 229, 'propulsion', False, False),
    TechCatalogEntry('tech_flak_batteries_3', 'Flak Batteries III', 4, 'engineering', ['tech_flak_batteries_2'], None, 230, 'propulsion', False, False),
    TechCatalogEntry('tech_food_processing_1', 'Food Processing I', 1, 'society', ['tech_eco_simulation'], None, 231, 'biology', False, False),
    TechCatalogEntry('tech_food_processing_2', 'Food Processing II', 3, 'society', ['tech_food_processing_1'], None, 232, 'biology', False, False),
    TechCatalogEntry('tech_frontier_health', 'Frontier Health', 1, 'society', ['tech_basic_health', 'tech_genome_mapping'], None, 233, 'biology', False, False),
    TechCatalogEntry('tech_frontier_hospital', 'Frontier Hospital', 2, 'society', ['tech_frontier_health', 'tech_colonial_centralization'], None, 234, 'biology', False, False),
    TechCatalogEntry('tech_ftl_inhibitor', 'Ftl Inhibitor', 2, 'physics', ['tech_hyper_drive_1'], None, 235, 'particles', False, False),
    TechCatalogEntry('tech_fusion_power', 'Fusion Power', 1, 'physics', ['tech_fission_power'], None, 236, 'particles', False, False),
    TechCatalogEntry('tech_galactic_administration', 'Galactic Administration', 3, 'society', ['tech_colonial_centralization'], None, 237, 'statecraft', False, False),
    TechCatalogEntry('tech_galactic_ambitions', 'Galactic Ambitions', 2, 'society', [], None, 238, 'new_worlds', False, False),
    TechCatalogEntry('tech_galactic_archivism', 'Galactic Archivism', 2, 'society', [], None, 239, 'statecraft', False, False),
    TechCatalogEntry('tech_galactic_bureaucracy', 'Galactic Bureaucracy', 3, 'society', ['tech_colonial_bureaucracy'], None, 240, 'statecraft', False, False),
    TechCatalogEntry('tech_galactic_campaigns', 'Galactic Campaigns', 4, 'society', ['tech_interstellar_campaigns'], None, 241, 'military_theory', False, False),
    TechCatalogEntry('tech_galactic_markets', 'Galactic Markets', 4, 'society', ['tech_colonial_centralization', 'tech_interstellar_economics'], None, 242, 'statecraft', True, False),
    TechCatalogEntry('tech_gargantuan_evolution', 'Gargantuan Evolution', 1, 'society', [], 'distant_stars', 243, 'biology', True, False),
    TechCatalogEntry('tech_gateway_activation', 'Gateway Activation', 4, 'physics', ['tech_hyper_drive_3'], None, 244, 'particles', True, False),
    TechCatalogEntry('tech_gateway_construction', 'Gateway Construction', 5, 'physics', ['tech_gateway_activation', 'tech_mega_engineering'], None, 245, 'particles', True, False),
    TechCatalogEntry('tech_gene_banks', 'Gene Banks', 2, 'society', ['tech_cloning'], None, 246, 'biology', True, False),
    TechCatalogEntry('tech_gene_crops', 'Gene Crops', 2, 'society', ['tech_eco_simulation'], None, 247, 'biology', False, False),
    TechCatalogEntry('tech_gene_expressions', 'Gene Expressions', 3, 'society', ['tech_gene_tailoring'], None, 248, 'biology', True, False),
    TechCatalogEntry('tech_gene_seed_purification', 'Gene Seed Purification', 4, 'society', ['tech_gene_tailoring'], None, 249, 'biology', True, False),
    TechCatalogEntry('tech_gene_tailoring', 'Gene Tailoring', 3, 'society', ['tech_genome_mapping'], None, 250, 'biology', False, False),
    TechCatalogEntry('tech_genome_mapping', 'Genome Mapping', 1, 'society', [], None, 251, 'biology', False, False),
    TechCatalogEntry('tech_georadiation_terraforming', 'Georadiation Terraforming', 3, 'society', [], None, 252, 'new_worlds', False, False),
    TechCatalogEntry('tech_glandular_acclimation', 'Glandular Acclimation', 3, 'society', ['tech_gene_tailoring'], None, 253, 'biology', False, False),
    TechCatalogEntry('tech_global_defense_grid', 'Global Defense Grid', 2, 'society', ['tech_ground_defense_planning'], None, 254, 'military_theory', False, False),
    TechCatalogEntry('tech_global_production_strategy', 'Global Production Strategy', 3, 'society', ['tech_alloys_1', 'tech_colonial_centralization'], None, 255, 'statecraft', False, False),
    TechCatalogEntry('tech_global_research_initiative', 'Global Research Initiative', 3, 'physics', ['tech_basic_science_lab_2', 'tech_colonial_centralization'], None, 256, 'computing', False, False),
    TechCatalogEntry('tech_gravity_snare_capacity_1', 'Gravity Snare Capacity I', 2, 'physics', ['tech_gravity_wells'], None, 257, 'field_manipulation', False, False),
    TechCatalogEntry('tech_gravity_snare_capacity_2', 'Gravity Snare Capacity II', 3, 'physics', ['tech_gravity_snare_capacity_1'], None, 258, 'field_manipulation', True, False),
    TechCatalogEntry('tech_gravity_snare_capacity_3', 'Gravity Snare Capacity III', 4, 'physics', ['tech_gravity_snare_capacity_2'], None, 259, 'field_manipulation', True, False),
    TechCatalogEntry('tech_gravity_wells', 'Gravity Wells', 2, 'physics', [], None, 260, 'field_manipulation', False, False),
    TechCatalogEntry('tech_ground_defense_planning', 'Ground Defense Planning', 1, 'society', ['tech_planetary_defenses'], None, 261, 'military_theory', False, False),
    TechCatalogEntry('tech_growth_chamber_1', 'Growth Chamber I', 4, 'society', ['tech_stingers', 'tech_mauler_growth_1', 'tech_stinger_growth_1', 'tech_weaver_growth_1', 'tech_harbinger_growth_1'], None, 262, 'biology', False, False),
    TechCatalogEntry('tech_growth_chamber_2', 'Growth Chamber II', 4, 'society', ['tech_growth_chamber_1', 'tech_mauler_growth_2', 'tech_stinger_growth_2', 'tech_weaver_growth_2', 'tech_harbinger_growth_2'], None, 263, 'biology', False, False),
    TechCatalogEntry('tech_habitat_1', 'Habitats I', 3, 'engineering', ['tech_starbase_3'], None, 264, 'voidcraft', False, False),
    TechCatalogEntry('tech_habitat_2', 'Habitats II', 4, 'engineering', ['tech_habitat_1', 'tech_starbase_4'], None, 265, 'voidcraft', True, False),
    TechCatalogEntry('tech_habitat_3', 'Habitats III', 4, 'engineering', ['tech_habitat_2', 'tech_starbase_5'], None, 266, 'voidcraft', True, False),
    TechCatalogEntry('tech_harbinger_build_speed', 'Harbinger Build Speed', 3, 'society', ['tech_harbingers'], None, 267, 'biology', False, False),
    TechCatalogEntry('tech_harbinger_growth_1', 'Harbinger Growth I', 3, 'society', ['tech_harbingers'], None, 268, 'biology', False, False),
    TechCatalogEntry('tech_harbinger_growth_2', 'Harbinger Growth II', 3, 'society', ['tech_harbinger_growth_1'], None, 269, 'biology', False, False),
    TechCatalogEntry('tech_harbingers', 'Harbingers', 3, 'society', ['tech_weavers'], None, 270, 'biology', False, False),
    TechCatalogEntry('tech_heritage_site', 'Heritage Site', 2, 'society', ['tech_cultural_heritage'], None, 271, 'statecraft', False, False),
    TechCatalogEntry('tech_hive_cluster', 'Hive Cluster', 2, 'society', ['tech_hive_node'], None, 272, 'statecraft', False, False),
    TechCatalogEntry('tech_hive_confluence', 'Hive Confluence', 3, 'society', ['tech_hive_cluster', 'tech_colonial_centralization'], None, 273, 'statecraft', False, False),
    TechCatalogEntry('tech_holographic_rituals', 'Holographic Rituals', 2, 'society', ['tech_planetary_government'], None, 274, 'statecraft', False, False),
    TechCatalogEntry('tech_housing_1', 'Housing I', 2, 'engineering', [], None, 275, 'industry', False, False),
    TechCatalogEntry('tech_housing_2', 'Housing II', 3, 'engineering', ['tech_housing_1'], None, 276, 'industry', False, False),
    TechCatalogEntry('tech_housing_agrarian_idyll', 'Housing Agrarian Idyll', 3, 'society', [], None, 277, 'statecraft', False, False),
    TechCatalogEntry('tech_hyper_drive_2', 'Hyper Drive II', 2, 'physics', ['tech_hyper_drive_1'], None, 278, 'particles', False, False),
    TechCatalogEntry('tech_hyper_drive_3', 'Hyper Drive III', 3, 'physics', ['tech_hyper_drive_2'], None, 279, 'particles', False, False),
    TechCatalogEntry('tech_hyper_drive_bio_integration', 'Hyper Drive Bio Integration', 2, 'physics', ['tech_controlled_mutations'], None, 280, 'particles', False, False),
    TechCatalogEntry('tech_hyper_entertainment_forum', 'Hyper Entertainment Forum', 1, 'society', ['tech_holo_entertainment'], None, 281, 'statecraft', False, False),
    TechCatalogEntry('tech_hyper_relays', 'Hyper Relays', 2, 'physics', ['tech_hyper_drive_2'], 'overlord', 282, 'particles', True, False),
    TechCatalogEntry('tech_hypercomms_forum', 'Hypercomms Forum', 3, 'society', ['tech_heritage_site', 'tech_colonial_centralization'], None, 283, 'statecraft', False, False),
    TechCatalogEntry('tech_identity_copy', 'Identity Copy', 4, 'engineering', [], 'machine_age', 284, 'industry', False, False),
    TechCatalogEntry('tech_identity_fusion', 'Identity Fusion', 4, 'engineering', [], 'machine_age', 285, 'industry', False, False),
    TechCatalogEntry('tech_identity_initialization', 'Identity Initialization', 4, 'engineering', [], 'machine_age', 286, 'industry', False, False),
    TechCatalogEntry('tech_improved_incubators', 'Improved Incubators', 2, 'society', ['tech_alien_cloning'], None, 287, 'biology', False, False),
    TechCatalogEntry('tech_industrial_storm_protection', 'Industrial Storm Protection', 1, 'engineering', [], None, 288, 'industry', False, False),
    TechCatalogEntry('tech_integrated_cybernetics', 'Integrated Cybernetics', 2, 'engineering', ['tech_powered_exoskeletons', 'tech_colonial_centralization'], None, 289, 'industry', False, False),
    TechCatalogEntry('tech_interstellar_assembly', 'Interstellar Assembly', 5, 'society', ['tech_mega_engineering'], None, 290, 'statecraft', True, False),
    TechCatalogEntry('tech_interstellar_campaigns', 'Interstellar Campaigns', 2, 'society', ['tech_galactic_ambitions'], None, 291, 'military_theory', False, False),
    TechCatalogEntry('tech_interstellar_economics', 'Interstellar Economics', 3, 'society', ['tech_space_trading'], None, 292, 'statecraft', False, False),
    TechCatalogEntry('tech_interstellar_fleet_traditions', 'Interstellar Fleet Traditions', 2, 'society', [], None, 293, 'military_theory', False, False),
    TechCatalogEntry('tech_juggernaut', 'Juggernaut', 5, 'engineering', ['tech_starbase_5', 'tech_battleships', 'tech_harbinger_growth_2'], None, 294, 'voidcraft', True, False),
    TechCatalogEntry('tech_jump_drive_1', 'Jump Drive', 5, 'physics', ['tech_zero_point_power'], None, 295, 'particles', True, True),
    TechCatalogEntry('tech_kinetic_artillery_1', 'Kinetic Artillery I', 3, 'engineering', ['tech_mass_drivers_4'], None, 296, 'propulsion', False, False),
    TechCatalogEntry('tech_kinetic_artillery_2', 'Kinetic Artillery II', 4, 'engineering', ['tech_mass_drivers_5', 'tech_kinetic_artillery_1'], None, 297, 'propulsion', False, False),
    TechCatalogEntry('tech_lasers_2', 'Lasers II', 1, 'physics', ['tech_lasers_1'], None, 298, 'particles', False, False),
    TechCatalogEntry('tech_lasers_3', 'Lasers III', 2, 'physics', ['tech_lasers_2'], None, 299, 'particles', False, False),
    TechCatalogEntry('tech_lasers_4', 'Lasers IV', 3, 'physics', ['tech_lasers_3'], None, 300, 'particles', False, False),
    TechCatalogEntry('tech_lasers_5', 'Lasers V', 4, 'physics', ['tech_lasers_4'], None, 301, 'particles', False, False),
    TechCatalogEntry('tech_lathe_cogitator', 'Lathe Cogitator', 5, 'society', [], 'machine_age', 302, 'military_theory', True, False),
    TechCatalogEntry('tech_lathe_life_support', 'Lathe Life Support', 5, 'society', [], 'machine_age', 303, 'biology', True, False),
    TechCatalogEntry('tech_lathe_overclocker', 'Lathe Overclocker', 5, 'physics', [], 'machine_age', 304, 'computing', True, False),
    TechCatalogEntry('tech_lathe_preserver', 'Lathe Preserver', 5, 'society', [], 'machine_age', 305, 'biology', True, False),
    TechCatalogEntry('tech_lathe_resonator', 'Lathe Resonator', 5, 'physics', [], 'machine_age', 306, 'computing', True, False),
    TechCatalogEntry('tech_lathe_validator', 'Lathe Validator', 5, 'physics', [], 'machine_age', 307, 'computing', True, False),
    TechCatalogEntry('tech_leviathan_techgenesis', 'Leviathan Techgenesis', 5, 'engineering', [], None, 308, 'industry', True, False),
    TechCatalogEntry('tech_lgate_activation', 'Lgate Activation', 3, 'physics', [], 'distant_stars', 309, 'particles', True, True),
    TechCatalogEntry('tech_living_state', 'Living State', 2, 'society', ['tech_colonial_centralization'], None, 310, 'statecraft', False, False),
    TechCatalogEntry('tech_living_test_subjects', 'Living Test Subjects', 1, 'society', [], None, 311, 'biology', False, False),
    TechCatalogEntry('tech_lost_building_methods', 'Lost Building Methods', 2, 'engineering', [], 'first_contact', 312, 'industry', False, False),
    TechCatalogEntry('tech_luxuries_1', 'Luxury Goods', 1, 'engineering', ['tech_basic_industry'], None, 313, 'materials', False, False),
    TechCatalogEntry('tech_luxuries_2', 'Luxuries II', 3, 'engineering', ['tech_luxuries_1', 'tech_colonial_centralization'], None, 314, 'materials', False, False),
    TechCatalogEntry('tech_mandibles_2', 'Mandibles II', 3, 'engineering', ['tech_maulers'], None, 315, 'materials', False, False),
    TechCatalogEntry('tech_mandibles_3', 'Mandibles III', 4, 'engineering', ['tech_mandibles_2'], None, 316, 'materials', False, False),
    TechCatalogEntry('tech_manifest_destiny', 'Manifest Destiny', 4, 'society', ['tech_galactic_ambitions'], None, 317, 'new_worlds', False, False),
    TechCatalogEntry('tech_mass_accelerator_1', 'Mass Accelerator I', 4, 'engineering', ['tech_mass_drivers_4', 'tech_battleships', 'tech_stingers'], None, 318, 'propulsion', False, False),
    TechCatalogEntry('tech_mass_accelerator_2', 'Mass Accelerator II', 4, 'engineering', ['tech_mass_drivers_5', 'tech_mass_accelerator_1'], None, 319, 'propulsion', False, False),
    TechCatalogEntry('tech_mass_drivers_2', 'Mass Drivers II', 1, 'engineering', ['tech_mass_drivers_1'], None, 320, 'propulsion', False, False),
    TechCatalogEntry('tech_mass_drivers_3', 'Mass Drivers III', 2, 'engineering', ['tech_mass_drivers_2'], None, 321, 'propulsion', False, False),
    TechCatalogEntry('tech_mass_drivers_4', 'Mass Drivers IV', 3, 'engineering', ['tech_mass_drivers_3'], None, 322, 'propulsion', False, False),
    TechCatalogEntry('tech_mass_drivers_5', 'Mass Drivers V', 4, 'engineering', ['tech_mass_drivers_4'], None, 323, 'propulsion', False, False),
    TechCatalogEntry('tech_massive_glacier', 'Massive Glacier', 1, 'society', ['tech_colonization_1'], None, 324, 'new_worlds', False, False),
    TechCatalogEntry('tech_materiality_engine', 'Materiality Engine', 3, 'society', [], None, 325, 'psionics', True, False),
    TechCatalogEntry('tech_matter_decompressor', 'Matter Decompressor', 5, 'physics', ['tech_mega_engineering'], None, 326, 'field_manipulation', True, False),
    TechCatalogEntry('tech_mauler_build_speed', 'Mauler Build Speed', 1, 'society', ['tech_maulers'], None, 327, 'biology', False, False),
    TechCatalogEntry('tech_mauler_growth_1', 'Mauler Growth I', 1, 'society', ['tech_maulers'], None, 328, 'biology', False, False),
    TechCatalogEntry('tech_mauler_growth_2', 'Mauler Growth II', 1, 'society', ['tech_mauler_growth_1'], None, 329, 'biology', False, False),
    TechCatalogEntry('tech_mega_art', 'Mega Art', 5, 'society', ['tech_mega_engineering'], None, 330, 'statecraft', True, False),
    TechCatalogEntry('tech_mega_assembly', 'Mega Assembly', 4, 'engineering', ['tech_binary_motivators', 'tech_galactic_administration'], None, 331, 'industry', True, False),
    TechCatalogEntry('tech_mega_engineering', 'Mega-Engineering', 5, 'engineering', ['tech_starbase_5', 'tech_zero_point_power', 'tech_battleships', 'tech_stingers'], None, 332, 'voidcraft', True, False),
    TechCatalogEntry('tech_mega_shipyard', 'Mega Shipyard', 5, 'society', ['tech_mega_engineering'], None, 333, 'military_theory', True, False),
    TechCatalogEntry('tech_metabolic_gases', 'Metabolic Gases', 3, 'society', ['tech_improved_incubators'], None, 334, 'biology', False, False),
    TechCatalogEntry('tech_micro_replicators', 'Micro Replicators', 2, 'engineering', [], None, 335, 'industry', False, False),
    TechCatalogEntry('tech_mine_betharian', 'Mine Betharian', 2, 'engineering', ['tech_space_construction'], None, 336, 'materials', False, False),
    TechCatalogEntry('tech_mine_dark_matter', 'Dark Matter Extraction', 3, 'physics', ['tech_sensors_4'], None, 337, 'field_manipulation', False, False),
    TechCatalogEntry('tech_mine_exotic_gases', 'Exotic Gas Extraction', 2, 'engineering', ['tech_space_construction'], None, 338, 'materials', False, False),
    TechCatalogEntry('tech_mine_living_metal', 'Living Metal Mining', 5, 'engineering', ['tech_space_construction'], None, 339, 'materials', False, False),
    TechCatalogEntry('tech_mine_rare_crystals', 'Rare Crystal Mining', 2, 'engineering', ['tech_space_construction'], None, 340, 'materials', False, False),
    TechCatalogEntry('tech_mine_volatile_motes', 'Volatile Mote Extraction', 2, 'physics', ['tech_space_construction'], None, 341, 'particles', False, False),
    TechCatalogEntry('tech_mine_zro', 'Zro Distillation', 3, 'society', ['tech_sensors_3'], None, 342, 'psionics', True, False),
    TechCatalogEntry('tech_mineral_purification_1', 'Mineral Purification', 1, 'engineering', ['tech_mining_1'], None, 343, 'industry', False, False),
    TechCatalogEntry('tech_mineral_purification_2', 'Advanced Mineral Purification', 2, 'engineering', ['tech_mineral_purification_1', 'tech_colonial_centralization'], None, 344, 'industry', False, False),
    TechCatalogEntry('tech_mining_1', 'Mining I', 1, 'engineering', ['tech_basic_industry'], None, 345, 'industry', False, False),
    TechCatalogEntry('tech_mining_2', 'Mining II', 2, 'engineering', ['tech_mining_1'], None, 346, 'industry', False, False),
    TechCatalogEntry('tech_mining_3', 'Mining III', 3, 'engineering', ['tech_mining_2'], None, 347, 'industry', False, False),
    TechCatalogEntry('tech_mining_drone_weapon_1', 'Mining Drone Weapon I', 2, 'physics', [], None, 348, 'particles', False, False),
    TechCatalogEntry('tech_missiles_2', 'Missiles II', 1, 'engineering', ['tech_missiles_1', 'tech_fusion_power'], None, 349, 'propulsion', False, False),
    TechCatalogEntry('tech_missiles_3', 'Missiles III', 2, 'engineering', ['tech_missiles_2'], None, 350, 'propulsion', False, False),
    TechCatalogEntry('tech_missiles_4', 'Missiles IV', 3, 'engineering', ['tech_missiles_3'], None, 351, 'propulsion', False, False),
    TechCatalogEntry('tech_missiles_5', 'Missiles V', 4, 'engineering', ['tech_missiles_4'], None, 352, 'propulsion', False, False),
    TechCatalogEntry('tech_modular_engineering', 'Modular Engineering', 2, 'engineering', ['tech_starbase_3'], None, 353, 'voidcraft', True, False),
    TechCatalogEntry('tech_morphogenetic_field_mastery', 'Morphogenetic Field Mastery', 4, 'society', ['tech_epigenetic_triggers'], None, 354, 'biology', True, False),
    TechCatalogEntry('tech_mountain_range', 'Mountain Range', 2, 'society', ['tech_colonization_1'], None, 355, 'new_worlds', False, False),
    TechCatalogEntry('tech_nanite_assemblers', 'Nanite Assemblers', 4, 'engineering', ['tech_binary_motivators', 'tech_galactic_administration'], None, 356, 'industry', True, False),
    TechCatalogEntry('tech_nanite_autocannon', 'Nanite Autocannon', 5, 'engineering', [], 'distant_stars', 357, 'propulsion', True, False),
    TechCatalogEntry('tech_nanite_flak_batteries', 'Nanite Flak Batteries', 5, 'engineering', [], 'distant_stars', 358, 'propulsion', True, False),
    TechCatalogEntry('tech_nanite_repair_system', 'Nanite Repair System', 5, 'engineering', [], 'distant_stars', 359, 'voidcraft', True, False),
    TechCatalogEntry('tech_nanite_repair_system_synth_queen', 'Nanite Repair System Synth Queen', 5, 'engineering', [], 'machine_age', 360, 'materials', True, False),
    TechCatalogEntry('tech_nanite_transmutation', 'Nanite Transmutation', 2, 'engineering', [], None, 361, 'materials', True, False),
    TechCatalogEntry('tech_nano_vitality_crops', 'Nano Vitality Crops', 3, 'society', ['tech_gene_crops'], None, 362, 'biology', False, False),
    TechCatalogEntry('tech_neural_implants', 'Neural Implants', 1, 'society', [], None, 363, 'statecraft', False, False),
    TechCatalogEntry('tech_neuro_quantum_links', 'Neuro Quantum Links', 3, 'physics', ['tech_basic_science_lab_2', 'tech_integrated_cybernetics'], None, 364, 'computing', False, False),
    TechCatalogEntry('tech_neuroregeneration', 'Neuroregeneration', 4, 'society', [], 'distant_stars', 365, 'biology', True, False),
    TechCatalogEntry('tech_new_numbers', 'New Numbers', 2, 'physics', [], 'first_contact', 366, 'computing', False, False),
    TechCatalogEntry('tech_node_culling_1', 'Node Culling I', 2, 'society', ['tech_colonial_centralization'], None, 367, 'statecraft', False, False),
    TechCatalogEntry('tech_node_culling_2', 'Node Culling II', 3, 'society', ['tech_node_culling_1'], None, 368, 'statecraft', False, False),
    TechCatalogEntry('tech_node_culling_3', 'Node Culling III', 4, 'society', ['tech_node_culling_2'], None, 369, 'statecraft', True, False),
    TechCatalogEntry('tech_node_reformatting_1', 'Node Reformatting I', 2, 'society', ['tech_colonial_centralization'], None, 370, 'statecraft', False, False),
    TechCatalogEntry('tech_node_reformatting_2', 'Node Reformatting II', 3, 'society', ['tech_node_reformatting_1'], None, 371, 'statecraft', False, False),
    TechCatalogEntry('tech_node_reformatting_3', 'Node Reformatting III', 4, 'society', ['tech_node_reformatting_2'], None, 372, 'statecraft', True, False),
    TechCatalogEntry('tech_noxious_swamp', 'Noxious Swamp', 1, 'society', ['tech_colonization_1'], None, 373, 'new_worlds', False, False),
    TechCatalogEntry('tech_nutrient_replication', 'Nutrient Replication', 4, 'society', ['tech_nano_vitality_crops'], None, 374, 'biology', True, False),
    TechCatalogEntry('tech_orbital_arc_furnace', 'Orbital Arc Furnace', 2, 'engineering', [], 'machine_age', 375, 'materials', True, False),
    TechCatalogEntry('tech_orbital_maneuvers', 'Orbital Maneuvers', 2, 'physics', [], None, 376, 'computing', False, False),
    TechCatalogEntry('tech_orbital_ring_tier_1', 'Orbital Ring Tier I', 3, 'engineering', ['tech_starbase_3', 'tech_galactic_administration', 'tech_planetary_infrastructure_1'], 'overlord', 377, 'voidcraft', False, False),
    TechCatalogEntry('tech_orbital_trash_dispersal', 'Orbital Trash Dispersal', 1, 'engineering', [], 'megacorp', 378, 'propulsion', True, False),
    TechCatalogEntry('tech_ordered_retreat', 'Ordered Retreat', 2, 'engineering', [], 'first_contact', 379, 'voidcraft', False, False),
    TechCatalogEntry('tech_paradise_dome', 'Paradise Dome', 3, 'society', ['tech_housing_1'], None, 380, 'statecraft', False, False),
    TechCatalogEntry('tech_pd_tracking_2', 'Pd Tracking II', 2, 'physics', ['tech_pd_tracking_1'], None, 381, 'computing', False, False),
    TechCatalogEntry('tech_pd_tracking_3', 'Pd Tracking III', 4, 'physics', ['tech_pd_tracking_2'], None, 382, 'computing', False, False),
    TechCatalogEntry('tech_penal_colonies', 'Penal Colonies', 2, 'society', ['tech_artificial_moral_codes'], None, 383, 'statecraft', True, False),
    TechCatalogEntry('tech_physics_1', 'Physics I', 1, 'physics', ['tech_basic_science_lab_1'], None, 384, 'field_manipulation', False, False),
    TechCatalogEntry('tech_physics_2', 'Physics II', 2, 'physics', ['tech_physics_1'], None, 385, 'field_manipulation', False, False),
    TechCatalogEntry('tech_physics_3', 'Physics III', 3, 'physics', ['tech_physics_2'], None, 386, 'field_manipulation', False, False),
    TechCatalogEntry('tech_pk_cracker', 'Pk Cracker', 5, 'engineering', ['tech_colossus'], 'apocalypse', 387, 'voidcraft', True, False),
    TechCatalogEntry('tech_pk_godray', 'Pk Godray', 5, 'society', ['tech_colossus'], 'apocalypse', 388, 'psionics', True, False),
    TechCatalogEntry('tech_pk_nanobots', 'Pk Nanobots', 5, 'engineering', ['tech_colossus'], 'apocalypse', 389, 'voidcraft', True, False),
    TechCatalogEntry('tech_pk_neutron', 'Pk Neutron', 5, 'physics', ['tech_colossus'], 'apocalypse', 390, 'particles', True, False),
    TechCatalogEntry('tech_pk_shielder', 'Pk Shielder', 5, 'physics', ['tech_colossus'], 'apocalypse', 391, 'field_manipulation', True, False),
    TechCatalogEntry('tech_pk_smelter', 'Pk Smelter', 5, 'engineering', ['tech_colossus'], 'apocalypse', 392, 'voidcraft', True, False),
    TechCatalogEntry('tech_planetary_infrastructure_1', 'Planetary Infrastructure I', 2, 'society', ['tech_colonial_centralization', 'tech_ship_armor_2'], None, 393, 'new_worlds', False, False),
    TechCatalogEntry('tech_planetary_infrastructure_2', 'Planetary Infrastructure II', 4, 'society', ['tech_galactic_administration', 'tech_ship_armor_4', 'tech_planetary_infrastructure_1'], None, 394, 'new_worlds', False, False),
    TechCatalogEntry('tech_planetary_shield_generator', 'Planetary Shield Generator', 3, 'physics', ['tech_shields_3'], None, 395, 'field_manipulation', True, False),
    TechCatalogEntry('tech_planetary_unification', 'Planetary Unification', 1, 'society', ['tech_planetary_government'], None, 396, 'statecraft', False, False),
    TechCatalogEntry('tech_plasma_1', 'Plasma I', 2, 'physics', ['tech_lasers_2'], None, 397, 'particles', False, False),
    TechCatalogEntry('tech_plasma_2', 'Plasma II', 3, 'physics', ['tech_plasma_1'], None, 398, 'particles', False, False),
    TechCatalogEntry('tech_plasma_3', 'Plasma III', 4, 'physics', ['tech_plasma_2'], None, 399, 'particles', False, False),
    TechCatalogEntry('tech_positronic_implants', 'Positronic Implants', 4, 'physics', ['tech_self_aware_logic'], None, 400, 'computing', False, False),
    TechCatalogEntry('tech_power_hub_1', 'Power Hub I', 1, 'physics', ['tech_power_plant_2'], None, 401, 'field_manipulation', False, False),
    TechCatalogEntry('tech_power_hub_2', 'Power Hub II', 2, 'physics', ['tech_power_hub_1', 'tech_colonial_centralization'], None, 402, 'field_manipulation', False, False),
    TechCatalogEntry('tech_power_plant_2', 'Power Plant II', 1, 'physics', ['tech_power_plant_1'], None, 403, 'field_manipulation', False, False),
    TechCatalogEntry('tech_power_plant_3', 'Power Plant III', 2, 'physics', ['tech_power_plant_2'], None, 404, 'field_manipulation', False, False),
    TechCatalogEntry('tech_power_plant_4', 'Power Plant IV', 3, 'physics', ['tech_power_plant_3'], None, 405, 'field_manipulation', False, False),
    TechCatalogEntry('tech_powered_exoskeletons', 'Powered Exoskeletons', 1, 'engineering', ['tech_basic_industry'], None, 406, 'industry', False, False),
    TechCatalogEntry('tech_precognition_interface', 'Precognition Interface', 4, 'society', ['tech_telepathy'], None, 407, 'psionics', True, False),
    TechCatalogEntry('tech_predatory_tactics', 'Predatory Tactics', 2, 'society', [], 'first_contact', 408, 'military_theory', False, False),
    TechCatalogEntry('tech_prescient_data_modeling', 'Prescient Data Modeling', 3, 'society', [], None, 409, 'statecraft', True, False),
    TechCatalogEntry('tech_psi_jump_drive_1', 'Psi Jump Drive', 5, 'society', ['tech_precognition_interface'], None, 410, 'psionics', True, True),
    TechCatalogEntry('tech_psionic_aura', 'Psionic Aura', 3, 'society', [], None, 411, 'psionics', True, False),
    TechCatalogEntry('tech_psionic_barrier', 'Psionic Barrier', 3, 'society', ['tech_psionic_theory'], None, 412, 'psionics', True, False),
    TechCatalogEntry('tech_psionic_bombers', 'Psionic Bombers', 5, 'society', [], None, 413, 'psionics', True, False),
    TechCatalogEntry('tech_psionic_disruptor', 'Psionic Disruptor', 5, 'society', [], None, 414, 'psionics', True, False),
    TechCatalogEntry('tech_psionic_lightning', 'Psionic Lightning', 5, 'society', [], None, 415, 'psionics', True, False),
    TechCatalogEntry('tech_psionic_shield', 'Psionic Shield', 5, 'society', ['tech_psionic_theory'], None, 416, 'psionics', True, False),
    TechCatalogEntry('tech_psionic_suppression', 'Psionic Suppression', 2, 'society', [], None, 417, 'psionics', False, False),
    TechCatalogEntry('tech_psionic_theory', 'Psionic Theory', 3, 'society', [], None, 418, 'psionics', True, False),
    TechCatalogEntry('tech_pyroclastic_resonation', 'Pyroclastic Resonation', 2, 'engineering', [], None, 419, 'industry', False, False),
    TechCatalogEntry('tech_quantum_catapult', 'Quantum Catapult', 3, 'physics', [], 'overlord', 420, 'particles', True, False),
    TechCatalogEntry('tech_quicksand_basin', 'Quicksand Basin', 1, 'society', ['tech_colonization_1'], None, 421, 'new_worlds', False, False),
    TechCatalogEntry('tech_rare_crystals', 'Rare Crystals', 2, 'engineering', ['tech_basic_industry'], None, 422, 'materials', False, False),
    TechCatalogEntry('tech_reactor_boosters_2', 'Reactor Boosters II', 1, 'physics', ['tech_fusion_power', 'tech_reactor_boosters_1'], None, 423, 'particles', False, False),
    TechCatalogEntry('tech_reactor_boosters_3', 'Reactor Boosters III', 1, 'physics', ['tech_antimatter_power', 'tech_reactor_boosters_2'], None, 424, 'particles', False, False),
    TechCatalogEntry('tech_refit_standards', 'Refit Standards', 3, 'society', ['tech_interstellar_fleet_traditions'], None, 425, 'military_theory', False, False),
    TechCatalogEntry('tech_regenerative_hull_tissue', 'Regenerative Hull Tissue', 3, 'society', [], None, 426, 'biology', True, False),
    TechCatalogEntry('tech_repeatable_lcluster_clue', 'Repeatable Lcluster Clue', 2, 'engineering', [], 'distant_stars', 427, 'voidcraft', True, True),
    TechCatalogEntry('tech_resort_colonies', 'Resort Colonies', 2, 'society', ['tech_artificial_moral_codes'], None, 428, 'statecraft', False, False),
    TechCatalogEntry('tech_resource_processing_algorithms', 'Resource Processing Algorithms', 3, 'society', ['tech_unity_of_purpose'], None, 429, 'statecraft', False, False),
    TechCatalogEntry('tech_rift_sphere', 'Rift Sphere', 2, 'physics', [], 'astral_planes', 430, 'field_manipulation', True, False),
    TechCatalogEntry('tech_ring_world', 'Ring World', 5, 'engineering', ['tech_mega_engineering'], None, 431, 'voidcraft', True, False),
    TechCatalogEntry('tech_robomodding', 'Robomodding', 1, 'engineering', ['tech_robotic_workers'], None, 432, 'industry', False, False),
    TechCatalogEntry('tech_robomodding_m', 'Robomodding M', 1, 'engineering', ['tech_powered_exoskeletons'], None, 433, 'industry', False, False),
    TechCatalogEntry('tech_robomodding_points_1', 'Robomodding Points I', 2, 'engineering', ['tech_robomodding', 'tech_droid_workers'], None, 434, 'industry', False, False),
    TechCatalogEntry('tech_robomodding_points_2', 'Robomodding Points II', 4, 'engineering', ['tech_robomodding_points_1', 'tech_synthetic_workers'], None, 435, 'industry', True, False),
    TechCatalogEntry('tech_robot_assembly_complex', 'Robot Assembly Complex', 4, 'engineering', ['tech_robomodding', 'tech_galactic_administration'], None, 436, 'industry', True, False),
    TechCatalogEntry('tech_robotic_workers', 'Robotic Workers', 1, 'engineering', ['tech_powered_exoskeletons'], None, 437, 'industry', False, False),
    TechCatalogEntry('tech_sapient_ai', 'Positronic AI', 4, 'physics', ['tech_self_aware_logic'], None, 438, 'computing', False, False),
    TechCatalogEntry('tech_satisfying_insults', 'Satisfying Insults', 2, 'society', [], 'first_contact', 439, 'statecraft', False, False),
    TechCatalogEntry('tech_science_nexus', 'Science Nexus', 5, 'physics', ['tech_mega_engineering'], None, 440, 'computing', True, False),
    TechCatalogEntry('tech_scourge_missile_1', 'Scourge Missile I', 5, 'society', [], None, 441, 'biology', True, False),
    TechCatalogEntry('tech_secrets_baol', 'Secrets Baol', 4, 'society', [], 'ancient_relics', 442, 'archaeostudies', True, False),
    TechCatalogEntry('tech_secrets_cybrex', 'Secrets Cybrex', 4, 'society', [], 'ancient_relics', 443, 'archaeostudies', True, False),
    TechCatalogEntry('tech_secrets_irassian', 'Secrets Irassian', 4, 'society', [], 'ancient_relics', 444, 'archaeostudies', True, False),
    TechCatalogEntry('tech_secrets_league', 'Secrets League', 4, 'society', [], 'ancient_relics', 445, 'archaeostudies', True, False),
    TechCatalogEntry('tech_secrets_vultaum', 'Secrets Vultaum', 4, 'society', [], 'ancient_relics', 446, 'archaeostudies', True, False),
    TechCatalogEntry('tech_secrets_yuht', 'Secrets Yuht', 4, 'society', [], 'ancient_relics', 447, 'archaeostudies', True, False),
    TechCatalogEntry('tech_secrets_zroni', 'Secrets Zroni', 4, 'society', [], 'ancient_relics', 448, 'archaeostudies', True, False),
    TechCatalogEntry('tech_selected_lineages', 'Selected Lineages', 3, 'society', ['tech_vitality_boosters'], None, 449, 'biology', True, False),
    TechCatalogEntry('tech_self_assembling_components', 'Self Assembling Components', 3, 'engineering', ['tech_micro_replicators'], None, 450, 'industry', False, False),
    TechCatalogEntry('tech_self_aware_logic', 'Self-Aware Logic', 2, 'physics', ['tech_administrative_ai'], None, 451, 'computing', False, False),
    TechCatalogEntry('tech_sensors_2', 'Sensors II', 2, 'physics', [], None, 452, 'computing', False, False),
    TechCatalogEntry('tech_sensors_3', 'Sensors III', 3, 'physics', ['tech_sensors_2'], None, 453, 'computing', False, False),
    TechCatalogEntry('tech_sensors_4', 'Sensors IV', 4, 'physics', ['tech_sensors_3'], None, 454, 'computing', False, False),
    TechCatalogEntry('tech_sensors_bio_integration', 'Sensors Bio Integration', 2, 'physics', ['tech_controlled_mutations'], None, 455, 'computing', False, False),
    TechCatalogEntry('tech_sentry_array', 'Sentry Array', 5, 'physics', ['tech_mega_engineering'], None, 456, 'computing', True, False),
    TechCatalogEntry('tech_shield_hardeners_1', 'Shield Hardeners I', 2, 'physics', ['tech_shield_rechargers_1', 'tech_exotic_gases'], None, 457, 'field_manipulation', False, False),
    TechCatalogEntry('tech_shield_hardeners_2', 'Shield Hardeners II', 5, 'physics', ['tech_shield_hardeners_1', 'tech_mine_zro'], None, 458, 'field_manipulation', False, False),
    TechCatalogEntry('tech_shield_rechargers_1', 'Shield Rechargers I', 2, 'physics', ['tech_shields_3'], None, 459, 'field_manipulation', False, False),
    TechCatalogEntry('tech_shields_2', 'Shields II', 1, 'physics', ['tech_shields_1'], None, 460, 'field_manipulation', False, False),
    TechCatalogEntry('tech_shields_3', 'Shields III', 2, 'physics', ['tech_shields_2'], None, 461, 'field_manipulation', False, False),
    TechCatalogEntry('tech_shields_4', 'Shields IV', 3, 'physics', ['tech_shields_3'], None, 462, 'field_manipulation', False, False),
    TechCatalogEntry('tech_shields_5', 'Shields V', 4, 'physics', ['tech_shields_4'], None, 463, 'field_manipulation', False, False),
    TechCatalogEntry('tech_ship_armor_2', 'Ship Armor II', 1, 'engineering', ['tech_ship_armor_1'], None, 464, 'materials', False, False),
    TechCatalogEntry('tech_ship_armor_3', 'Ship Armor III', 2, 'engineering', ['tech_ship_armor_2'], None, 465, 'materials', False, False),
    TechCatalogEntry('tech_ship_armor_4', 'Ship Armor IV', 3, 'engineering', ['tech_ship_armor_3'], None, 466, 'materials', False, False),
    TechCatalogEntry('tech_ship_armor_5', 'Ship Armor V', 4, 'engineering', ['tech_ship_armor_4'], None, 467, 'materials', False, False),
    TechCatalogEntry('tech_ship_hull_storm_breaker_1', 'Ship Hull Storm Breaker I', 1, 'engineering', ['tech_storm_prediction_1'], None, 468, 'materials', False, False),
    TechCatalogEntry('tech_ship_hull_storm_breaker_2', 'Ship Hull Storm Breaker II', 2, 'engineering', ['tech_ship_hull_storm_breaker_1'], None, 469, 'materials', False, False),
    TechCatalogEntry('tech_ship_storm_weapons_1', 'Ship Storm Weapons I', 1, 'engineering', ['tech_storm_prediction_1'], None, 470, 'voidcraft', False, False),
    TechCatalogEntry('tech_ship_storm_weapons_2', 'Ship Storm Weapons II', 2, 'engineering', ['tech_ship_storm_weapons_1'], None, 471, 'voidcraft', False, False),
    TechCatalogEntry('tech_slave_colonies', 'Slave Colonies', 2, 'society', ['tech_neural_implants'], None, 472, 'statecraft', False, False),
    TechCatalogEntry('tech_society_1', 'Society I', 1, 'society', ['tech_basic_science_lab_1'], None, 473, 'biology', False, False),
    TechCatalogEntry('tech_society_2', 'Society II', 2, 'society', ['tech_society_1'], None, 474, 'biology', False, False),
    TechCatalogEntry('tech_society_3', 'Society III', 3, 'society', ['tech_society_2'], None, 475, 'biology', False, False),
    TechCatalogEntry('tech_space_cloud_weapon_1', 'Space Cloud Weapon I', 2, 'physics', [], None, 476, 'particles', True, False),
    TechCatalogEntry('tech_space_defense_station_improvement', 'Space Defense Station Improvement', 3, 'engineering', ['tech_starbase_4', 'tech_modular_engineering'], None, 477, 'voidcraft', True, False),
    TechCatalogEntry('tech_space_mining_1', 'Space Mining I', 1, 'engineering', ['tech_space_construction'], None, 478, 'industry', False, False),
    TechCatalogEntry('tech_space_mining_2', 'Space Mining II', 1, 'engineering', ['tech_space_mining_1'], None, 479, 'industry', False, False),
    TechCatalogEntry('tech_space_mining_3', 'Space Mining III', 2, 'engineering', ['tech_space_mining_2'], None, 480, 'industry', False, False),
    TechCatalogEntry('tech_space_mining_4', 'Space Mining IV', 2, 'engineering', ['tech_space_mining_3'], None, 481, 'industry', False, False),
    TechCatalogEntry('tech_space_mining_5', 'Space Mining V', 3, 'engineering', ['tech_space_mining_4'], None, 482, 'industry', False, False),
    TechCatalogEntry('tech_space_science_1', 'Space Science I', 1, 'physics', ['tech_space_construction'], None, 483, 'computing', False, False),
    TechCatalogEntry('tech_space_science_2', 'Space Science II', 1, 'physics', ['tech_space_science_1'], None, 484, 'computing', False, False),
    TechCatalogEntry('tech_space_science_3', 'Space Science III', 2, 'physics', ['tech_space_science_2'], None, 485, 'computing', False, False),
    TechCatalogEntry('tech_space_science_4', 'Space Science IV', 2, 'physics', ['tech_space_science_3'], None, 486, 'computing', False, False),
    TechCatalogEntry('tech_space_science_5', 'Space Science V', 3, 'physics', ['tech_space_science_4'], None, 487, 'computing', False, False),
    TechCatalogEntry('tech_space_trading', 'Space Trading', 1, 'society', ['tech_interplanetary_commerce'], None, 488, 'statecraft', False, False),
    TechCatalogEntry('tech_space_whale_weapon_1', 'Space Whale Weapon I', 1, 'society', [], None, 489, 'biology', False, False),
    TechCatalogEntry('tech_starbase_3', 'Starbase Construction III', 2, 'engineering', ['tech_starbase_2'], None, 490, 'voidcraft', False, False),
    TechCatalogEntry('tech_starbase_4', 'Starbase Construction IV', 3, 'engineering', ['tech_starbase_3'], None, 491, 'voidcraft', False, False),
    TechCatalogEntry('tech_starbase_5', 'Starbase Construction V', 4, 'engineering', ['tech_starbase_4'], None, 492, 'voidcraft', False, False),
    TechCatalogEntry('tech_starfire_cannon', 'Starfire Cannon', 4, 'physics', [], None, 493, 'particles', True, False),
    TechCatalogEntry('tech_stinger_build_speed', 'Stinger Build Speed', 4, 'society', ['tech_stingers'], None, 494, 'biology', False, False),
    TechCatalogEntry('tech_stinger_growth_1', 'Stinger Growth I', 4, 'society', ['tech_stingers'], None, 495, 'biology', False, False),
    TechCatalogEntry('tech_stinger_growth_2', 'Stinger Growth II', 4, 'society', ['tech_stinger_growth_1'], None, 496, 'biology', False, False),
    TechCatalogEntry('tech_stingers', 'Stingers', 4, 'society', ['tech_harbingers'], None, 497, 'biology', False, False),
    TechCatalogEntry('tech_storm_manipulation', 'Storm Manipulation', 2, 'physics', ['tech_industrial_storm_protection'], None, 498, 'field_manipulation', False, False),
    TechCatalogEntry('tech_storm_prediction_1', 'Storm Prediction I', 1, 'physics', ['tech_industrial_storm_protection'], None, 499, 'computing', False, False),
    TechCatalogEntry('tech_storm_prediction_2', 'Storm Prediction II', 3, 'physics', ['tech_storm_prediction_1'], None, 500, 'computing', True, False),
    TechCatalogEntry('tech_strategic_coordination', 'Strategic Coordination', 5, 'society', ['tech_mega_engineering'], None, 501, 'military_theory', True, False),
    TechCatalogEntry('tech_strike_craft_1', 'Strike Craft I', 1, 'engineering', ['tech_starbase_2'], None, 502, 'voidcraft', False, False),
    TechCatalogEntry('tech_strike_craft_2', 'Strike Craft II', 2, 'engineering', ['tech_strike_craft_1'], None, 503, 'voidcraft', False, False),
    TechCatalogEntry('tech_strike_craft_3', 'Strike Craft III', 3, 'engineering', ['tech_strike_craft_2'], None, 504, 'voidcraft', False, False),
    TechCatalogEntry('tech_strike_craft_skrand', 'Strike Craft Skrand', 4, 'engineering', [], None, 505, 'voidcraft', True, False),
    TechCatalogEntry('tech_subdermal_stimulation', 'Subdermal Stimulation', 2, 'society', ['tech_genome_mapping'], None, 506, 'biology', True, False),
    TechCatalogEntry('tech_supreme_alloy', 'Supreme Alloy', 2, 'engineering', [], 'first_contact', 507, 'materials', False, False),
    TechCatalogEntry('tech_swarm_strike_craft_1', 'Swarm Strike Craft I', 5, 'society', [], None, 508, 'biology', True, False),
    TechCatalogEntry('tech_swarmer_missiles_1', 'Swarmer Missiles I', 2, 'engineering', ['tech_harbingers', 'tech_stingers', 'tech_missiles_2'], None, 509, 'propulsion', False, False),
    TechCatalogEntry('tech_swarmer_missiles_2', 'Swarmer Missiles II', 4, 'engineering', ['tech_swarmer_missiles_1'], None, 510, 'propulsion', False, False),
    TechCatalogEntry('tech_synchronized_defences', 'Synchronized Defences', 4, 'physics', ['tech_self_aware_logic'], None, 511, 'computing', True, False),
    TechCatalogEntry('tech_synth_queen_knowledge', 'Synth Queen Knowledge', 5, 'physics', [], 'machine_age', 512, 'computing', True, False),
    TechCatalogEntry('tech_synthetic_leaders', 'Synthetic Leaders', 4, 'engineering', ['tech_synthetic_workers'], None, 513, 'industry', False, False),
    TechCatalogEntry('tech_synthetic_thought_patterns', 'Synthetic Thought Patterns', 3, 'society', ['tech_artificial_moral_codes'], None, 514, 'statecraft', False, False),
    TechCatalogEntry('tech_synthetic_workers', 'Synthetics', 4, 'engineering', ['tech_droid_workers', 'tech_galactic_administration', 'tech_sapient_ai'], None, 515, 'industry', True, True),
    TechCatalogEntry('tech_telepathy', 'Telepathy', 3, 'society', ['tech_psionic_theory'], None, 516, 'psionics', True, False),
    TechCatalogEntry('tech_temple_of_transportation', 'Temple of Transportation', 2, 'engineering', [], 'first_contact', 517, 'voidcraft', False, False),
    TechCatalogEntry('tech_terrestrial_sculpting', 'Terrestrial Sculpting', 2, 'society', ['tech_colonization_1'], None, 518, 'new_worlds', False, False),
    TechCatalogEntry('tech_thought_enforcement', 'Thought Enforcement', 4, 'society', ['tech_telepathy'], None, 519, 'psionics', True, False),
    TechCatalogEntry('tech_thrusters_2', 'Thrusters II', 2, 'engineering', ['tech_thrusters_1'], None, 520, 'propulsion', False, False),
    TechCatalogEntry('tech_thrusters_3', 'Thrusters III', 3, 'engineering', ['tech_thrusters_2'], None, 521, 'propulsion', False, False),
    TechCatalogEntry('tech_thrusters_4', 'Thrusters IV', 4, 'engineering', ['tech_thrusters_3'], None, 522, 'propulsion', False, False),
    TechCatalogEntry('tech_thrusters_bio_integration', 'Thrusters Bio Integration', 2, 'engineering', ['tech_controlled_mutations'], None, 523, 'propulsion', False, False),
    TechCatalogEntry('tech_titan_hull_1', 'Titan Hull I', 5, 'engineering', ['tech_titans'], None, 524, 'voidcraft', True, False),
    TechCatalogEntry('tech_titan_hull_2', 'Titan Hull II', 5, 'engineering', ['tech_titan_hull_1'], None, 525, 'voidcraft', True, False),
    TechCatalogEntry('tech_titans', 'Titans', 5, 'engineering', ['tech_battleships', 'tech_stinger_growth_2'], None, 526, 'voidcraft', False, False),
    TechCatalogEntry('tech_tomb_world_adaption', 'Tomb World Adaption', 3, 'society', ['tech_colonization_3'], None, 527, 'new_worlds', True, False),
    TechCatalogEntry('tech_torpedoes_1', 'Torpedoes I', 1, 'engineering', ['tech_corvettes'], None, 528, 'propulsion', False, False),
    TechCatalogEntry('tech_torpedoes_2', 'Torpedoes II', 3, 'engineering', ['tech_torpedoes_1'], None, 529, 'propulsion', False, False),
    TechCatalogEntry('tech_torpedoes_3', 'Torpedoes III', 4, 'engineering', ['tech_torpedoes_2'], None, 530, 'propulsion', False, False),
    TechCatalogEntry('tech_toxic_kelp', 'Toxic Kelp', 1, 'society', ['tech_colonization_1'], None, 531, 'new_worlds', False, False),
    TechCatalogEntry('tech_tracking_implants', 'Tracking Implants', 4, 'society', ['tech_subdermal_stimulation', 'tech_galactic_bureaucracy'], None, 532, 'statecraft', True, False),
    TechCatalogEntry('tech_transcendent_faith', 'Transcendent Faith', 4, 'society', ['tech_consecration_fields', 'tech_galactic_administration'], None, 533, 'statecraft', False, False),
    TechCatalogEntry('tech_trinary_computing', 'Trinary Computing', 2, 'physics', [], 'first_contact', 534, 'computing', False, False),
    TechCatalogEntry('tech_unique_mutation_crystalline_entity', 'Unique Mutation Crystalline Entity', 3, 'society', ['tech_controlled_mutations_2'], None, 535, 'biology', False, False),
    TechCatalogEntry('tech_unique_mutation_cutholoid', 'Unique Mutation Cutholoid', 3, 'society', ['tech_controlled_mutations_2'], None, 536, 'biology', False, False),
    TechCatalogEntry('tech_unique_mutation_restorative_enzymes', 'Unique Mutation Restorative Enzymes', 4, 'society', ['tech_controlled_mutations_2'], None, 537, 'biology', False, False),
    TechCatalogEntry('tech_unique_mutation_space_amoeba', 'Unique Mutation Space Amoeba', 3, 'society', ['tech_controlled_mutations_2'], None, 538, 'biology', False, False),
    TechCatalogEntry('tech_unique_mutation_starborne_biology', 'Unique Mutation Starborne Biology', 4, 'society', ['tech_controlled_mutations_2'], None, 539, 'biology', False, False),
    TechCatalogEntry('tech_unique_mutation_tiyanki', 'Unique Mutation Tiyanki', 3, 'society', ['tech_controlled_mutations_2'], None, 540, 'biology', False, False),
    TechCatalogEntry('tech_unique_mutation_voidworm', 'Unique Mutation Voidworm', 3, 'society', ['tech_controlled_mutations_2'], None, 541, 'biology', False, False),
    TechCatalogEntry('tech_unity_of_purpose', 'Unity of Purpose', 2, 'society', [], None, 542, 'statecraft', False, False),
    TechCatalogEntry('tech_universal_marcophage', 'Universal Marcophage', 3, 'society', [], None, 543, 'biology', True, False),
    TechCatalogEntry('tech_unusual_senses', 'Unusual Senses', 2, 'physics', [], 'first_contact', 544, 'particles', False, False),
    TechCatalogEntry('tech_vitality_boosters', 'Vitality Boosters', 2, 'society', ['tech_genome_mapping'], None, 545, 'biology', False, False),
    TechCatalogEntry('tech_voidworm_immunity', 'Voidworm Immunity', 3, 'society', [], None, 546, 'biology', False, False),
    TechCatalogEntry('tech_volatile_motes', 'Volatile Motes', 2, 'physics', ['tech_basic_industry'], None, 547, 'particles', False, False),
    TechCatalogEntry('tech_volcanic_forge', 'Volcanic Forge', 2, 'society', [], None, 548, 'new_worlds', True, False),
    TechCatalogEntry('tech_volcanic_terraforming', 'Volcanic Terraforming', 2, 'society', ['tech_terrestrial_sculpting', 'tech_volcano'], None, 549, 'new_worlds', True, False),
    TechCatalogEntry('tech_volcano', 'Volcano', 2, 'society', ['tech_colonization_1'], None, 550, 'new_worlds', False, False),
    TechCatalogEntry('tech_weaver_bio_anti_evasion_2', 'Weaver Bio Anti Evasion II', 2, 'society', ['tech_weaver_bio_anti_evasion_1'], None, 551, 'biology', False, False),
    TechCatalogEntry('tech_weaver_bio_anti_evasion_3', 'Weaver Bio Anti Evasion III', 3, 'society', ['tech_weaver_bio_anti_evasion_2'], None, 552, 'biology', False, False),
    TechCatalogEntry('tech_weaver_bio_anti_evasion_4', 'Weaver Bio Anti Evasion IV', 4, 'society', ['tech_weaver_bio_anti_evasion_3'], None, 553, 'biology', False, False),
    TechCatalogEntry('tech_weaver_bio_anti_evasion_5', 'Weaver Bio Anti Evasion V', 5, 'society', ['tech_weaver_bio_anti_evasion_4'], None, 554, 'biology', False, False),
    TechCatalogEntry('tech_weaver_bio_anti_evasion_6', 'Weaver Bio Anti Evasion 6', 0, 'society', ['tech_weaver_bio_anti_evasion_5'], None, 555, 'biology', True, False),
    TechCatalogEntry('tech_weaver_bio_anti_fire_rate_1', 'Weaver Bio Anti Fire Rate I', 1, 'society', ['tech_weavers'], None, 556, 'biology', False, False),
    TechCatalogEntry('tech_weaver_bio_anti_fire_rate_2', 'Weaver Bio Anti Fire Rate II', 2, 'society', ['tech_weaver_bio_anti_fire_rate_1'], None, 557, 'biology', False, False),
    TechCatalogEntry('tech_weaver_bio_anti_fire_rate_3', 'Weaver Bio Anti Fire Rate III', 3, 'society', ['tech_weaver_bio_anti_fire_rate_2'], None, 558, 'biology', False, False),
    TechCatalogEntry('tech_weaver_bio_anti_fire_rate_4', 'Weaver Bio Anti Fire Rate IV', 4, 'society', ['tech_weaver_bio_anti_fire_rate_3'], None, 559, 'biology', False, False),
    TechCatalogEntry('tech_weaver_bio_anti_fire_rate_5', 'Weaver Bio Anti Fire Rate V', 5, 'society', ['tech_weaver_bio_anti_fire_rate_4'], None, 560, 'biology', False, False),
    TechCatalogEntry('tech_weaver_bio_anti_fire_rate_6', 'Weaver Bio Anti Fire Rate 6', 0, 'society', ['tech_weaver_bio_anti_fire_rate_5'], None, 561, 'biology', True, False),
    TechCatalogEntry('tech_weaver_bio_confuser_1', 'Weaver Bio Confuser I', 1, 'society', ['tech_weavers'], None, 562, 'biology', False, False),
    TechCatalogEntry('tech_weaver_bio_confuser_2', 'Weaver Bio Confuser II', 2, 'society', ['tech_weaver_bio_confuser_1'], None, 563, 'biology', False, False),
    TechCatalogEntry('tech_weaver_bio_confuser_3', 'Weaver Bio Confuser III', 3, 'society', ['tech_weaver_bio_confuser_2'], None, 564, 'biology', False, False),
    TechCatalogEntry('tech_weaver_bio_confuser_4', 'Weaver Bio Confuser IV', 4, 'society', ['tech_weaver_bio_confuser_3'], None, 565, 'biology', False, False),
    TechCatalogEntry('tech_weaver_bio_confuser_5', 'Weaver Bio Confuser V', 5, 'society', ['tech_weaver_bio_confuser_4'], None, 566, 'biology', False, False),
    TechCatalogEntry('tech_weaver_bio_confuser_6', 'Weaver Bio Confuser 6', 0, 'society', ['tech_weaver_bio_confuser_5'], None, 567, 'biology', True, False),
    TechCatalogEntry('tech_weaver_bio_evasion_2', 'Weaver Bio Evasion II', 2, 'society', ['tech_weaver_bio_evasion_1'], None, 568, 'biology', False, False),
    TechCatalogEntry('tech_weaver_bio_evasion_3', 'Weaver Bio Evasion III', 3, 'society', ['tech_weaver_bio_evasion_2'], None, 569, 'biology', False, False),
    TechCatalogEntry('tech_weaver_bio_evasion_4', 'Weaver Bio Evasion IV', 4, 'society', ['tech_weaver_bio_evasion_3'], None, 570, 'biology', False, False),
    TechCatalogEntry('tech_weaver_bio_evasion_5', 'Weaver Bio Evasion V', 5, 'society', ['tech_weaver_bio_evasion_4'], None, 571, 'biology', False, False),
    TechCatalogEntry('tech_weaver_bio_evasion_6', 'Weaver Bio Evasion 6', 0, 'society', ['tech_weaver_bio_evasion_5'], None, 572, 'biology', True, False),
    TechCatalogEntry('tech_weaver_bio_fire_rate_1', 'Weaver Bio Fire Rate I', 1, 'society', ['tech_weavers'], None, 573, 'biology', False, False),
    TechCatalogEntry('tech_weaver_bio_fire_rate_2', 'Weaver Bio Fire Rate II', 2, 'society', ['tech_weaver_bio_fire_rate_1'], None, 574, 'biology', False, False),
    TechCatalogEntry('tech_weaver_bio_fire_rate_3', 'Weaver Bio Fire Rate III', 3, 'society', ['tech_weaver_bio_fire_rate_2'], None, 575, 'biology', False, False),
    TechCatalogEntry('tech_weaver_bio_fire_rate_4', 'Weaver Bio Fire Rate IV', 4, 'society', ['tech_weaver_bio_fire_rate_3'], None, 576, 'biology', False, False),
    TechCatalogEntry('tech_weaver_bio_fire_rate_5', 'Weaver Bio Fire Rate V', 5, 'society', ['tech_weaver_bio_fire_rate_4'], None, 577, 'biology', False, False),
    TechCatalogEntry('tech_weaver_bio_fire_rate_6', 'Weaver Bio Fire Rate 6', 0, 'society', ['tech_weaver_bio_fire_rate_5'], None, 578, 'biology', True, False),
    TechCatalogEntry('tech_weaver_bio_healing_1', 'Weaver Bio Healing I', 1, 'society', ['tech_weavers'], None, 579, 'biology', False, False),
    TechCatalogEntry('tech_weaver_bio_healing_2', 'Weaver Bio Healing II', 2, 'society', ['tech_weaver_bio_healing_1'], None, 580, 'biology', False, False),
    TechCatalogEntry('tech_weaver_bio_healing_3', 'Weaver Bio Healing III', 3, 'society', ['tech_weaver_bio_healing_2'], None, 581, 'biology', False, False),
    TechCatalogEntry('tech_weaver_bio_healing_4', 'Weaver Bio Healing IV', 4, 'society', ['tech_weaver_bio_healing_3'], None, 582, 'biology', False, False),
    TechCatalogEntry('tech_weaver_bio_healing_5', 'Weaver Bio Healing V', 5, 'society', ['tech_weaver_bio_healing_4'], None, 583, 'biology', False, False),
    TechCatalogEntry('tech_weaver_bio_healing_6', 'Weaver Bio Healing 6', 0, 'society', ['tech_weaver_bio_healing_5'], None, 584, 'biology', True, False),
    TechCatalogEntry('tech_weaver_build_speed', 'Weaver Build Speed', 1, 'society', ['tech_weavers'], None, 585, 'biology', False, False),
    TechCatalogEntry('tech_weaver_growth_1', 'Weaver Growth I', 2, 'society', ['tech_weavers'], None, 586, 'biology', False, False),
    TechCatalogEntry('tech_weaver_growth_2', 'Weaver Growth II', 2, 'society', ['tech_weaver_growth_1'], None, 587, 'biology', False, False),
    TechCatalogEntry('tech_wilderness_cluster', 'Wilderness Cluster', 2, 'society', ['tech_wilderness_node'], None, 588, 'statecraft', False, False),
    TechCatalogEntry('tech_wilderness_confluence', 'Wilderness Confluence', 3, 'society', ['tech_wilderness_cluster', 'tech_colonial_centralization'], None, 589, 'statecraft', False, False),
    TechCatalogEntry('tech_wormhole_stabilization', 'Wormhole Stabilization', 3, 'physics', ['tech_hyper_drive_2'], None, 590, 'particles', True, False),
    TechCatalogEntry('tech_xeno_aesthetics', 'Xeno Aesthetics', 2, 'society', [], 'first_contact', 591, 'statecraft', False, False),
    TechCatalogEntry('tech_xeno_diplomacy', 'Xeno Diplomacy', 2, 'society', ['tech_federation_code'], None, 592, 'statecraft', False, False),
    TechCatalogEntry('tech_xeno_linguistics', 'Xeno Linguistics', 1, 'society', [], None, 593, 'statecraft', True, False),
    TechCatalogEntry('tech_xeno_relations', 'Xeno Relations', 3, 'society', ['tech_xeno_diplomacy', 'tech_galactic_administration'], None, 594, 'statecraft', False, False),
    TechCatalogEntry('tech_xeno_tourism_agency', 'Xeno Tourism Agency', 3, 'society', [], 'megacorp', 595, 'statecraft', False, False),
    TechCatalogEntry('tech_zero_point_power', 'Zero Point Power', 4, 'physics', ['tech_antimatter_power'], None, 596, 'particles', False, False),
    TechCatalogEntry('tech_zro_launcher', 'Zro Launcher', 5, 'society', [], None, 597, 'psionics', True, False),
]

# Default selection is empty: the player picks which techs to randomize
# via the Tech Config dashboard tab. The apworld accepts an empty set.
_DEFAULT_KEYS: List[str] = [
]


def by_key() -> Dict[str, TechCatalogEntry]:
    """Lookup table from tech key to catalog entry."""
    return {t.key: t for t in TECH_CATALOG}


def all_keys() -> List[str]:
    """All tech keys in the catalog, in offset order."""
    return [t.key for t in TECH_CATALOG]


def default_selection() -> List[str]:
    """Tech keys randomized when the player does not customize.

    Empty by default; the dashboard's Tech Config tab is the path
    to populate this. Returning an empty list keeps the seed lean
    until the player explicitly chooses what to randomize.
    """
    return list(_DEFAULT_KEYS)


def location_name(entry: TechCatalogEntry) -> str:
    """The AP location name shown to players."""
    return f"Research {entry.display}"


def item_name(entry: TechCatalogEntry) -> str:
    """The AP item name carried in the multiworld."""
    return f"Tech: {entry.display}"


def _validate():
    """Sanity-check the catalog at module load."""
    seen_keys = set()
    seen_offsets = set()
    for t in TECH_CATALOG:
        if t.key in seen_keys:
            raise ValueError(f"Tech catalog: duplicate key {t.key!r}")
        if t.offset in seen_offsets:
            raise ValueError(f"Tech catalog: duplicate offset {t.offset} on {t.key!r}")
        if t.area not in {"physics", "society", "engineering"}:
            raise ValueError(f"Tech catalog: invalid area {t.area!r} on {t.key!r}")
        if t.tier < 0 or t.tier > 5:
            raise ValueError(f"Tech catalog: tier {t.tier} out of range on {t.key!r}")
        seen_keys.add(t.key)
        seen_offsets.add(t.offset)


_validate()
